export const newSrCases = [
  [
    `Novinarka N1 Žaklina Tatalović dobila je preteće poruke preko društvenih mreža. Tatalović je primila pretnje smrću i uvrede na račun njenog rada sa profila "Alma Begović" i "Sabo Zoltan". Pretnje su prijavljene policiji od strane Tatalović i UNS-a.`,
    `Žaklini Tatalović  prećeno preko društvenih mreža`,
    `2023-03-29`,
    ``,
    `Medijski sektor`,
    `Nepoznato`,
    `Prevare, pretnje i manipulacije`,
    `Ugrožavanje sigurnosti`,
    `Direktne pretnje nasiljem uključujući pretnje koje su seksualne ili fizičke prirode`,
    `Ograničavanje slobode izražavanja`,
    `Verbalni napadi`,
    ``,
    ``,
    `Uznemiravanje`,
    `Direktne pretnje nasiljem uključujući pretnje koje su seksualne ili fizičke prirode`,
    ``,
    ``,
    `https://www.uns.org.rs/sr/saopstenja/143328/uns-tuzilastvo-za-vtk-da-pronadje-ko-preti-smrcu-zaklini-tatalovic.html`,
    ``,
    ``,
    `https://archive.li/DZb2R`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Gradonačelnik Aleksandar Šapić je tužio BIRN Srbija, glavnog i odgovornog urednika Milorada Ivanovića i novinare Jelenu Veljković, Aleksandra Đorđevića i Radmila Markovića zbog navodno iznetih neistina o njegovoj vili u Trstu i ozakonjenju gradnje na Bežanijskoj kosi. Tužbe su podnete zbog povrede časti, ugleda i ljudskog dostojanstva, a Šapić tvrdi da su iznete informacije prouzrokovale neizmernu štetu i povrede časti i ugleda.`,
    `Privatna tužba na račun BIRN Srbija`,
    `2023-03-29`,
    ``,
    `Medijski sektor`,
    `Politički subjekt`,
    `Prevare, pretnje i manipulacije`,
    `Ograničavanje slobode izražavanja`,
    `Zloupotreba pravnih mehanizama`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://birn.rs/sapic-tuzio-birn/`,
    ``,
    ``,
    `https://archive.li/jQpph`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Internet stranica i veb-server Agencije za privredne registre su bili meta napada Distributed Denial-of-Service (DDoS). Agencija je uspešno odbranila sistem u ponedeljak i omogućila pristup svim svojim veb-servisima, uz povremene prekide, a sistem sada nesmetano radi. Agencija je prijavila DDoS napade Nacionalnom centru za prevenciju bezbednosnih rizika u IKT sistemima (Nacionalni CERT) i Ministarstvu informisanja i telekomunikacija.`,
    `Sajt APR nedostupan usled tehničkog napada`,
    `2023-03-27`,
    ``,
    `Javni sektor`,
    `Nepoznato`,
    `Sajber incidenti`,
    `Onesposobljen servis`,
    `DoS/DDoS`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.slobodnaevropa.org/a/sajt-apr-sajber-napad/32336304.html`,
    `https://apr.gov.rs/vesti.2428.html?newsId=3618`,
    ``,
    `https://archive.ph/F6C5c`,
    `https://archive.ph/dOhYQ`,
    ``,
    ``,
    ``,
  ],
  [
    `Ekstremistički pokret "Konzervativni pokret Naši" poslao je pretnju na zvaničnu mejl adresu NDNV, optužujući organizaciju i portal Autonomija za to da su "strani plaćenici" koji vode "medijski rat protiv Rusije i Srbije" i "promovišu Ukrajinski neonacizam". U mejlu su posebno targetirali programskog direktora NDNV Dinka Gruhonjića i kolumnistu Autonomije Teofila Pančića.`,
    `NDNV-u stigle pretnje na zvaničnu mejl adresu`,
    `2023-03-15`,
    ``,
    `Medijski sektor`,
    `Građani`,
    `Prevare, pretnje i manipulacije`,
    `Ugrožavanje sigurnosti`,
    `Verbalni napadi`,
    `Ograničavanje slobode izražavanja`,
    `Verbalni napadi`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://ndnv.org/2023/03/16/ndnv-na-meti-ekstremista-institucije-da-sprece-fasizaciju-drustva/`,
    ``,
    ``,
    `https://archive.li/Xo0WR`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Fišing kampanja sa lažnim e-računom, logom i imenom kompanije Yettel kružila je na internetu. Iako je e-račun izgledao skoro identično kao računi Yettel-a, korisnici su upozoreni da obrate pažnju na domen.`,
    `Fišing kampanja sa lažnim e-računom Yettel-a`,
    `2023-03-20`,
    ``,
    `Građani`,
    `Nepoznato`,
    `Sajber incidenti`,
    `Onlajn prevare`,
    `Socijalni inženjering (fišing/vishing/smishing, lažno predstavljanje)`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.linkedin.com/posts/dragan-jovanovi%C4%87-a4481627_ponovo-problemati%C4%8Dna-phishing-aktivnost-na-activity-7039563333691138048-fCro/`,
    ``,
    ``,
    `https://archive.ph/YZWHV`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Istraživački novinar i urednik KRIK-a Stevan Dojčinović je govorio o životnom putu kriminalaca i regrutovanju mladića u navijačke grupe na podcastu Snaga uma. Nakon toga, na TikTok-u se pojavio komentar koji sugeriše da Dojčinovića treba ubiti. Ova javna pretnja ubistvom je prijavljena Posebnom tužilaštvu za borbu protiv visokotehnološkog kriminala.`,
    `Pretnje Stevanu Dojčinoviću na Tik Tok-u`,
    `2023-03-07`,
    ``,
    `Medijski sektor`,
    `Nepoznato`,
    `Prevare, pretnje i manipulacije`,
    `Ugrožavanje sigurnosti`,
    `Direktne pretnje nasiljem uključujući pretnje koje su seksualne ili fizičke prirode`,
    `Ograničavanje slobode izražavanja`,
    `Verbalni napadi`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://nova.rs/vesti/drustvo/stevan-dojcinovic-dobio-pretnje-ubistvom-nakon-gostovanja-na-nova-rs-slucaj-prijavljen/`,
    ``,
    ``,
    `https://archive.li/PGdDA`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Šaip Kamberi, poslanik u Skupštini Srbije i šef poslaničke grupe „Ujedinjena dolina i SDA Sandžak“ dobio je pretnje smrću preko Fejsbuka od osobe koja se potpisuje kao Danijel Milković.`,
    `Narodnom poslaniku prećeno preko Fejsbuka`,
    `2023-02-25`,
    ``,
    `Politički subjekt`,
    `Građani`,
    `Prevare, pretnje i manipulacije`,
    `Ugrožavanje sigurnosti`,
    `Direktne pretnje nasiljem uključujući pretnje koje su seksualne ili fizičke prirode`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://n1info.rs/vesti/kamberi-dobio-pretnje-smrcu-nikad-neces-znati-kada-dolazim-po-tvoju-glavu/`,
    ``,
    ``,
    `https://archive.ph/YMBE8`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Napravljen je lažni nalog političara i diplomate Milana St. Protića na Tviteru. Protić uopšte nema otvoren nalog na tviteru.`,
    `Lažni nalog Milana St. Protića na Tviteru`,
    `2023-02-11`,
    ``,
    `Javne ličnosti`,
    `Nepoznato`,
    `Prevare, pretnje i manipulacije`,
    `Ugrožavanje reputacije`,
    `Kreiranje lažnih sadržaja i naloga`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/strani_placenik/status/1624404461572456453`,
    ``,
    ``,
    `https://archive.ph/YGeSs`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `BIRN Srbija našao se pred Višim sudom u Beogradu pošto je Vlasnik kompanije Jovanjica, podneo tužbu protiv BIRN-a pod tvrdnjom da su o njemu objavljenje neistine. BIRN Srbija smatra da ova tužba predstavlja pokušaj zastrašivanje medija kako ne bi pisali o određenim temama ili ličnostima.`,
    `Protiv BIRN-a Srbija podneta je privatna tužba`,
    `2023-02-13`,
    ``,
    `Medijski sektor`,
    `Politički subjekt`,
    `Prevare, pretnje i manipulacije`,
    `Ograničavanje slobode izražavanja`,
    `Zloupotreba pravnih mehanizama`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://birn.rs/predrag-koluvija-tuzio-birn/`,
    ``,
    ``,
    `https://archive.ph/dP7xK`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Novinar portala Nova.rs Pero Jovović dobio je pretnje preko Tvitera. Slučaj je prijavio Tužilaštvu za visokotehnoločki kriminal. Udruženje novinara Srbije osudilo je pretnje.`,
    `Pretnje upućene novinaru na Tviteru`,
    `2023-02-09`,
    ``,
    `Medijski sektor`,
    `Građani`,
    `Prevare, pretnje i manipulacije`,
    `Ugrožavanje sigurnosti`,
    `Direktne pretnje nasiljem uključujući pretnje koje su seksualne ili fizičke prirode`,
    `Diskriminacija i govor mržnje`,
    `Napadi koji se temelje na rodu i seksualnoj orijentaciji`,
    ``,
    ``,
    `Uznemiravanje`,
    `Napadi koji se temelje na rodu i seksualnoj orijentaciji`,
    `Uznemiravanje`,
    `Direktne pretnje nasiljem uključujući pretnje koje su seksualne ili fizičke prirode`,
    `https://www.cenzolovka.rs/pritisci-i-napadi/jezive-pretnje-novinaru-peru-jovovicu-treba-ti-staviti-pistolj-na-celo-i-opaliti-metak-bez-trunke-savesti/`,
    ``,
    ``,
    `https://archive.is/5mOG7`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Na Instagram nalog novinarke Radija 021 Gorice Nikolin upućen je niz uvreda i pretnji nakon što je objavila tekst o ateljeima na Petrovaradinskoj tvrđavi koji se kako se navodi u tekstu, nelegalno koriste.`,
    `Pretnje upućene novinarki preko Instagrama`,
    `2023-01-31`,
    ``,
    `Medijski sektor`,
    `Građani`,
    `Prevare, pretnje i manipulacije`,
    `Ugrožavanje sigurnosti`,
    `Direktne pretnje nasiljem uključujući pretnje koje su seksualne ili fizičke prirode`,
    `Ograničavanje slobode izražavanja`,
    `Verbalni napadi`,
    ``,
    ``,
    `Uznemiravanje`,
    `Direktne pretnje nasiljem uključujući pretnje koje su seksualne ili fizičke prirode`,
    ``,
    ``,
    `https://nuns.rs/nuns-procesuirati-pretnje-novinarki-gorici-nikolin/`,
    ``,
    ``,
    `https://archive.li/I4qI0`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Portal Danas objavio je intervju sa nepostojećom osobom. Naime lažni nalog Daniela Smith-a postojao je na Tviteru i imao je za cilj da širi različiti propagandni sadržaj. Nakon objavljenog teksta na portalu, nalog je Daniela Smith-a je obrisan.`,
    `Portal Danas je objavio intervju sa nepostojećim ekspertom`,
    `2023-02-05`,
    ``,
    `Građani`,
    `Medijski sektor`,
    `Prevare, pretnje i manipulacije`,
    `Dezinformisanje javnosti`,
    `Kreiranje i deljenje lažnih sadržaja`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/frankblack2000/status/1621934449649745921?s=12&t=Z8pmNXycdRDEko4E2Z0cLQ`,
    `https://www.danas.rs/dijalog/licni-stavovi/sta-smo-naucili-iz-slucaja-daniel-smith/`,
    ``,
    `https://web.archive.org/web/20230206102011/https://twitter.com/frankblack2000/status/1621934449649745921?s=12&t=Z8pmNXycdRDEko4E2Z0cLQ`,
    `https://archive.li/oqYH3`,
    ``,
    ``,
    ``,
  ],
  [
    `Navodno u ime Doma zdravlja Stara Pazova i portala Moj doktor, građanima su stizali mejlovi sa zlonamernim / malicioznim prilozima sa ciljem da se zaraze računari građana.`,
    `Zloupotreba mejl adrese DZ Stara Pazova`,
    `2023-01-25`,
    ``,
    `Građani`,
    `Nepoznato`,
    `Sajber incidenti`,
    `Onlajn prevare`,
    `Socijalni inženjering (fišing/vishing/smishing, lažno predstavljanje)`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/ivanmarkovicsec/status/1618269721346068480`,
    ``,
    ``,
    `https://archive.ph/bk6RS`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Petar Đurić, predsednik udruženja građana „Pokret Ćale ovo je za tebe“ priveden je kako navodi njegov advokat nakon objave na Tviteru u kojoj kritikuje predsednika. Privela ga je Služba za borbu protiv organizovanog kriminala (SBPOK) i nakon ispitivanja pušten je na slobodu.`,
    `Aktivista priveden zbog svog tvita o predsedniku`,
    `2023-01-16`,
    ``,
    `Civilni sektor`,
    `Organi vlasti`,
    `Prevare, pretnje i manipulacije`,
    `Ograničavanje slobode izražavanja`,
    `Zloupotreba pravnih mehanizama`,
    `Ograničavanje slobode izražavanja`,
    `Odmazda za iznete stavove`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.danas.rs/vesti/politika/petar-djuric-priveden-u-sbpok-advokat-stojkovic-tvrdi-da-mu-nisu-dozvolili-da-ga-vidi/`,
    ``,
    ``,
    `https://archive.ph/TaEN6`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Kopredsednica stranke Zajedno Biljana Stojković dobila je, kako navodi do sada najnajgrozniju pretnju u svojoj slikovitosti i namerama. Pretnju je dobila preko društvene mreže Tviter i slučaj je prijavila policiji.`,
    `Pretnje političarki preko Tvitera`,
    `2023-01-16`,
    ``,
    `Politički subjekt`,
    `Nepoznato`,
    `Prevare, pretnje i manipulacije`,
    `Ugrožavanje sigurnosti`,
    `Direktne pretnje nasiljem uključujući pretnje koje su seksualne ili fizičke prirode`,
    ``,
    ``,
    ``,
    ``,
    `Uznemiravanje`,
    `Direktne pretnje nasiljem uključujući pretnje koje su seksualne ili fizičke prirode`,
    ``,
    ``,
    `https://n1info.rs/vesti/biljana-stojkovic-prijavila-policiji-pretnju-smrcu/`,
    ``,
    ``,
    `https://archive.ph/WC8nD`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Na Tviter profilu @ivanmarkovicsec objavljeni su detalji fišing kampanje koja zloupotrebljava logotip Pošte Srbije. Poruke kruže po Viberu. Kako se navodi domen vaxvjhjxd[.]cyou je kupljen preko registra u Kini.`,
    `Fišing kampanja sa brendom Pošte Srbije na Viberu`,
    `2023-01-11`,
    ``,
    `Građani`,
    `Nepoznato`,
    `Sajber incidenti`,
    `Onlajn prevare`,
    `Socijalni inženjering (fišing/vishing/smishing, lažno predstavljanje)`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/ivanmarkovicsec/status/1613242320253747201?t=fEa4AlhWJt-mU2VjaLfEhg&s=35`,
    ``,
    ``,
    `https://archive.li/BRcy3`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Nenad Paunović, novinar iz Pirota, priveden je u policiju sa još jednom osobom nakon što su pokušali da dronom snime mesto nesrece i to u danu kada je bilo planirano podizanje oštećene cisterne na prugu. Nakon ispitivanja i četvrosatnog zadržavanja oni su pušteni.`,
    `Novinar iz Pirota priveden zbog izveštavanja o nesreći`,
    `2023-01-11`,
    ``,
    `Medijski sektor`,
    `Organi vlasti`,
    `Prevare, pretnje i manipulacije`,
    `Ograničavanje slobode izražavanja`,
    `Zloupotreba pravnih mehanizama`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.cenzolovka.rs/pritisci-i-napadi/novinar-iz-pirota-povodom-privodjenja-zbog-snimanja-akcidenta-ne-mogu-da-mi-oproste-ministarku-i-mrtvog-turcina-koga-sam-nasao/`,
    ``,
    ``,
    `https://archive.li/CM9fd`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Po društvenim mrežama i medijima izašle su informacije o napadima na vebsajtove državnih institucija, konkretno: vojske, Min. odbrane, Min. spoljnih poslova, MUP-a, Aleksandra Vučića (vucic.rs).`,
    `DDoS napadi na sajtove državnih ministarstava`,
    `2023-01-06`,
    ``,
    `Javni sektor`,
    `Nepoznato`,
    `Sajber incidenti`,
    `Onesposobljen servis`,
    `DoS/DDoS`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/ivanmarkovicsec/status/1610957828583219200?t=9h-ODE5wMC-fufFIZ-SicQ&s=35`,
    `https://twitter.com/ivanmarkovicsec/status/1611034259757613057?t=_lVNfVsSDlZESTlofIO9_g&s=35`,
    `https://www.slobodnaevropa.org/a/srbija-napadi-anonymous-institucije-sajtovi-serveri/32215930.html`,
    `https://archive.ph/IPGEj`,
    `https://archive.ph/M0kG5`,
    `https://archive.li/L2v44`,
    ``,
    ``,
  ],
  [
    `Kompanija Yettel obavestila je građane o lažnoj nagradnoj igri koja je kružila na sajtovima na internetu, konkretno je zabeležen maliziozni pop-up prozor na sajtu za konvertovanje YouTube videa u mp3 format. Navodno se nakon popunjavanja ankete, dobijaju vredne nagrade.`,
    `Lažna nagradna igra navodno u ime kompanije Yettel`,
    `2023-02-27`,
    ``,
    `Građani`,
    `Nepoznato`,
    `Sajber incidenti`,
    `Onlajn prevare`,
    `Socijalni inženjering (fišing/vishing/smishing, lažno predstavljanje)`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.linkedin.com/feed/update/urn:li:activity:7036256371142500352/`,
    ``,
    ``,
    `https://archive.li/mYzf9`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Početkom godine bila je aktivna fišing kampanja koja targetira SBB korisnike preko mejla, gde su korisnicima stizali lažni mejlovi sa obaveštenjem o navodnom problemu sa obnavljanjem usluga i upućivali ih na lažnu stranicu http://eunet.co.rs.`,
    `Fišing kampanja usmerena na SBB korisnike`,
    `2023-01-03`,
    ``,
    `Građani`,
    `Nepoznato`,
    `Sajber incidenti`,
    `Onlajn prevare`,
    `Socijalni inženjering (fišing/vishing/smishing, lažno predstavljanje)`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/ivanmarkovicsec/status/1610227799373086721?t=gVpNtg_P-fZqlMRqfd3Auw&s=35`,
    ``,
    ``,
    `https://archive.li/34WlP`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Nekoliko dana nakon masovne pucnjave u osnovnoj školi u Beogradu, TikTok-om su počeli da kruže snimci iz škole navodno snimljeni za vreme masakra. Brzo je otkriveno da je video zapravo prikazuje drugi incident koji se desio pre nekoliko godina u školi u Sjedinjenim Državama.`,
    `Lažni snimci masakra iz beogradske osnovne škole deljeni na društvenim mrežama`,
    `2023-05-06`,
    ``,
    `Građani`,
    `Nepoznato`,
    `Prevare, pretnje i manipulacije`,
    `Dezinformisanje javnosti`,
    `Manipulacija sadržaja`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/mina_vrbaski/status/1654610887741784064`,
    ``,
    ``,
    `https://archive.li/ckfyy`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Novinar dnevnog lista Danas Nikola Krstić dobio je brojne pretnje nasiljem na društvenim mrežama nakon što je napisao tekst o izjavi patrijarha Srpske pravoslavne crkve Porfirija. Krstić je u tekstu komentarisao uvredljivu izjavu koju je poglavar SPC uputio ženama u Srbiji.`,
    `Pretnje novinaru zbog teksta o patrijarhu`,
    `2023-05-18`,
    ``,
    `Medijski sektor`,
    `Građani`,
    `Prevare, pretnje i manipulacije`,
    `Ugrožavanje sigurnosti`,
    `Direktne pretnje nasiljem uključujući pretnje koje su seksualne ili fizičke prirode`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://kossev.info/safejournalist-zahteva-da-se-pronadju-osobe-koje-su-pretile-novinaru-lista-danas-nakon-teksta-o-patrijarhu-spc/`,
    `https://twitter.com/krkela_krle/status/1659113155413286912?s=20`,
    ``,
    `https://archive.li/yD8L3`,
    `https://archive.li/9RsDz`,
    ``,
    ``,
    ``,
  ],
  [
    `Istraživački portal KRIK osuđen je prvostepenom presudom Višeg suda u Beogradu zbog objavljivanja teksta o tome ko je sve podnosio tužbe protiv ovog medija. Trojica pripadnika policije, koji su već podnosili tužbe i spominju se u tekstu, ponovo su tužili KRIK. Medij je već prvostepenom sudskom odlukom dužan da isplati skoro 3.200 evra na ime naknade štete za pretrpljenje duševne bolove, kao i da obriše delove teksta u kome se spominju pripadnici policije. KRIK je najavio da će se žaliti na presudu.`,
    `Istraživački portal osuđen zbog objavljivanja ko ih je tužio`,
    `2023-05-18`,
    ``,
    `Medijski sektor`,
    `Organi vlasti`,
    `Prevare, pretnje i manipulacije`,
    `Ograničavanje slobode izražavanja`,
    `Zloupotreba pravnih mehanizama`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.krik.rs/krik-osudjen-jer-je-objavio-ko-je-tuzio-redakciju-presudu-doneo-sudija-keranovic-poznat-po-procesu-protiv-nin-a/`,
    ``,
    ``,
    `https://archive.li/LcUKR`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Tabloidni portal Republika je senzacionalističkim izveštavanjem sa sahrane ubijenih u masakru u okolini Mladenovca koji se desio 4. maja. Nezavisno udruženje novinara Srbije pozvalo je novinare da poštuje privatnost, dostojanstvo i integritet ljudi o kojima pišu, naročito kada je reč o tragedijama.`,
    `Portal Republika ugrozio privatnost porodica žrtava masakra`,
    `2023-05-09`,
    ``,
    `Pojedinačna povreda`,
    `Odgovorno lice iz medijskog sektora`,
    `Privatnost i zaštita podataka`,
    `Objavljivanje podataka`,
    `Objavljivanje u medijima`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://nuns.rs/nuns-portal-republika-da-postuje-kodeks-i-prava-na-privatnost-porodica-zrtava/`,
    ``,
    ``,
    `https://archive.li/99uCd`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `U danima nakon višestrukog ubistva u beogradskoj osnovnoj školi "Vladislav Ribnikar", na sajtovima medija u Srbiji i regionu i društvenim mrežama objavljene su brojne dezinformacije u vezi sa događajem. Između ostalog, prenete su netačne informacije da je i ranjena nastavnica preminula, da vakcinisani građani ne mogu da budu donatori krvi, kao i da je televizija N1 tražila puštanje na slobodu osumnjičenog.`,
    `Brojne dezinformacije o ubistvima u školi u Beogradu`,
    `2023-05-08`,
    ``,
    `Građani`,
    `Medijski sektor`,
    `Prevare, pretnje i manipulacije`,
    `Dezinformisanje javnosti`,
    `Kreiranje i deljenje lažnih sadržaja`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.cenzolovka.rs/mediologija/dezinformacije-o-masakru-u-skoli-vladislav-ribnikar/`,
    ``,
    ``,
    `https://archive.li/9lkDY`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Narodna poslanica Staša Stojanović verbalno je napala zamenicu predsednika Demokratske stranke, isto narodnu poslanicu, Draganu Rakić na Tviteru nakon što je Rakić podelila video u kojem se vidi kako je Stojanović provocira u skupštini kao odgovor na protest dela opozicije na jučerašnjem zasedanju.`,
    `Narodna poslanica vladajuće stranke uputila uvrede poslanici opozicije na Tviteru`,
    `2023-05-25`,
    ``,
    `Politički subjekt`,
    `Politički subjekt`,
    `Prevare, pretnje i manipulacije`,
    `Diskriminacija i govor mržnje`,
    `Verbalni napadi`,
    ``,
    ``,
    ``,
    ``,
    `Uznemiravanje`,
    `Napadi koji se temelje na rodu i seksualnoj orijentaciji`,
    ``,
    ``,
    `https://twitter.com/stasasns/status/1661776299877183490?s=46`,
    ``,
    ``,
    `https://archive.li/14iY8`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Na Instagram nalogu poznatog srpskog pevača Šabana Šaulića objavljen je poziv za miting podrške predsedniku Aleksandru Vučiću i Srpskoj naprednoj stranci u Beogradu zakazan za 26. maj. Veliki broj javnih ličnosti podelio je poziv na svojim nalozima, ali je Šaulić jedini koji je to uradio posthumno.`,
    `Preminuli srpski pevač pozvao preko Instagrama na SNS miting`,
    `2023-05-24`,
    ``,
    `Građani`,
    `Politički subjekt`,
    `Prevare, pretnje i manipulacije`,
    `Dezinformisanje javnosti`,
    `Manipulacija sadržaja`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/NikolaLaki3/status/1661340279469744128`,
    `https://direktno.rs/vesti/drustvo-i-ekonomija/472153/saban-saulic-miting-vucic.html`,
    ``,
    `https://archive.li/hhfb8`,
    `https://archive.li/8Dd2e`,
    ``,
    ``,
    ``,
  ],
  [
    `Olja Bećković, autorka i voditeljka emisije „Utisak nedelje“ dobila je na svoj privatni broj telefona uznemirujuće poruke od predsednika Udruženja porodica kidnapovanih, ubijenih i nestalih sa prostora Kosova i Metohije Sima Spasića.`,
    `Voditeljka dobila pretnje na svoj privatni broj`,
    `2023-04-10`,
    ``,
    `Medijski sektor`,
    `Politički subjekt`,
    `Prevare, pretnje i manipulacije`,
    `Ugrožavanje sigurnosti`,
    `Direktne pretnje nasiljem uključujući pretnje koje su seksualne ili fizičke prirode`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.danas.rs/vesti/drustvo/nisam-prijavila-ovo-nije-prvi-put-simo-spasic-pretio-i-olji-beckovic/`,
    ``,
    ``,
    `https://archive.ph/j4DkG`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Voditelj Ivan Ivanović primio je eksplicitne pretnje na privatni broj od predsednika Udruženja porodica kidnapovanih, ubijenih i nestalih sa prostora Kosova i Metohije Sima Spasića. Spasić je takođe uputio ozbiljne mizogine i eksplicitne pretnje članicama Ivanovićeve porodice. Spasić je uhapšen 19.06. zbog ugrožavanja sigurnosti voditelja.`,
    `Voditelj dobio pretnje na privatni broj`,
    `2023-04-09`,
    ``,
    `Javne ličnosti`,
    `Politički subjekt`,
    `Prevare, pretnje i manipulacije`,
    `Ugrožavanje sigurnosti`,
    `Direktne pretnje nasiljem uključujući pretnje koje su seksualne ili fizičke prirode`,
    ``,
    ``,
    ``,
    ``,
    `Uznemiravanje`,
    `Direktne pretnje nasiljem uključujući pretnje koje su seksualne ili fizičke prirode`,
    ``,
    ``,
    `https://twitter.com/veceivan/status/1645172873055592448?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1645172873055592448%7Ctwgr%5E100438cb9068f82acf9c09eea99539560e35709a%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fwww.danas.rs%2Fvesti%2Fdrustvo%2Fivanu-ivanovicu-i-njegovoj-porodici-vulgarne-pretnje-uputio-simo-spasic%2F`,
    `https://n1info.rs/vesti/uhapsen-simo-spasic-zbog-ugrozavanja-sigurnosti-ivana-ivanovica/`,
    ``,
    `https://archive.li/9viel`,
    `https://archive.li/M8egA`,
    ``,
    ``,
    ``,
  ],
  [
    `Pevač Vlado Georgiev pretio je novinarima Nova.rs koji su objavili tekst o njegovoj firmi ,,Dunav kargo'' koju je otvorio 2020. godine i koja se bavi prevozom tereta unutrašnjim plovnim putevima. Objavili su istorijat firme i finansijske izveštaje.`,
    `Pevač pretio novinarima zbog teksta o njegovoj firmi`,
    `2023-04-10`,
    ``,
    `Medijski sektor`,
    `Javne ličnosti`,
    `Prevare, pretnje i manipulacije`,
    `Ugrožavanje sigurnosti`,
    `Direktne pretnje nasiljem uključujući pretnje koje su seksualne ili fizičke prirode`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://nova.rs/zabava/showbiz/trazicu-te-po-gradu-skandalozne-pretnje-vlada-georgieva-redakciji-nova-rs-nakon-pitanja-o-njegovom-biznisu/`,
    ``,
    ``,
    `https://archive.ph/SJ0nA`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Večernje novosti su obrisale sa sajta tekst o ambasadoru SAD u Srbiji Kristoferu Hilu. Tekst je postao nedostupan iako se po internet pretrazi i agregatorima vesti vidi da je bio objavljen. U tekstu su pored detalja iz života ambasadora Hila navedene brojne negativne kvalifikacije o njegovom odnosu prema Srbiji i srpskom narodu. Novosti su poznate kao medij sa pretežno anti-zapadnom uređivačkom politikom.`,
    `Novosti obrisale tekst o ambasadoru SAD`,
    `2023-04-04`,
    ``,
    `Građani`,
    `Medijski sektor`,
    `Prevare, pretnje i manipulacije`,
    `Autocenzura`,
    `Uklanjanje sadržaja`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://n1info.rs/vesti/vecernje-novosti-objavile-pa-obrisale-pamflet-o-ambasadoru-kristoferu-hilu/`,
    `https://time.rs/c/179ed6dde6/diplomata-koji-ni-je-voleo-srbiju-mrznja-prema-srbima-pod-velom-maslinove-grancice.html`,
    ``,
    `https://archive.li/CI6m6`,
    `https://archive.li/6w4Pe`,
    ``,
    ``,
    ``,
  ],
  [
    `Folk pevačica Jelena Karleuša je na svom Instagramu tažila od narodne poslanice Marinike Tepić da se izjasni o svojoj nacionalnoj pripadnosti, navodeći da u slučaju da se ne identifikuje kao srpkinja nema prava da učestvuje u protestima i kritikuje vlast jer 'ideološki' ne pripada srpskom narodu. Pevačica je prethodno javno podržala predsednika Vučića i kritikovala umetrnike, prevashodno glumice i glumce zbog izražavanja negativnih stavova usmerenih prema vlasti i učestvovanja u protestima "Srbija protiv nasilja".`,
    `Pevačica Jelena Karleuša vređala narodnu poslanicu Mariniku Tepić po nacionalnoj osnovi`,
    `2023-05-28`,
    ``,
    `Politički subjekt`,
    `Javne ličnosti`,
    `Prevare, pretnje i manipulacije`,
    `Diskriminacija i govor mržnje`,
    `Napadi na osnovu rasne, verske, nacionalne ili etničke pripadnosti`,
    `Ugrožavanje reputacije`,
    `Verbalni napadi`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/amfibolije/status/1662834561221554181?s=46`,
    `https://twitter.com/charliewafflees/status/1663543162395320321?s=46`,
    ``,
    `https://archive.li/AXLKR`,
    `https://archive.li/NINrU`,
    ``,
    ``,
    `mozda fali napad na osnovu verske, etnicke ili druge pripadnosti ali koji nije organizovani napad nego je jedan na jedan`,
  ],
  [
    `Politički komentator Nebojša Krstić na svom Tviter profilu podelio je fotografiju glumca Nikole Koja sa protesta "Srbija protiv nasilja" održanog 27. maja. Kojo je na protestu nosio natpis sa imenom Majora Omera Mehića koji je 2015. godine stravično nastradao u padu helikoptera koji je ostao nerazjašnjen ali se spekuliše da je povezan sa nekompetencijom vlasti. Krstić je podelio fotografiju i zamenio ime na transparentu sa porukom "Srbi trpe nasilje na Kosovu". Krstić je već danima aktivan na Tviteru gde napada opoziciju i kritikuje proteste. `,
    `Nebojša Krstić fabrikovao fotografiju glumca Nikole Koje na Tviteru`,
    `2023-05-29`,
    ``,
    `Javne ličnosti`,
    `Javne ličnosti`,
    `Prevare, pretnje i manipulacije`,
    `Dezinformisanje javnosti`,
    `Manipulacija sadržaja`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/CenzurisanoL/status/1663123104288190464?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1663221586021826560%7Ctwgr%5Eac34f6ca4d5296c5a26e9725546f7d3d47ec8da9%7Ctwcon%5Es3_&ref_url=https%3A%2F%2Fnova.rs%2Fvesti%2Fpolitika%2Fnebojsa-krstic-probio-dno-kada-je-napao-nikolu-koja-stigao-je-snazan-odgovor-glumca%2F`,
    `https://citymagazine.danas.rs/scena/drustvene-mreze/nebojsa-krstic-je-pokusao-da-bude-drustveno-angazovan-i-duhovit/`,
    ``,
    `https://archive.is/1lGMs`,
    `https://archive.li/jsBT2`,
    ``,
    ``,
    ``,
  ],
  [
    `Aktivista Gej strejt alijanse Lazar Pavlović, koji je na protestu "Srbija protiv nasilja" sa ženom i detetom šetao u majici "Lešinar tata" kao odgovor na način na koji je vlast okarakterisala demonstrante koji su šetali ulicama, već sutradan je napadnut na društvenim mrežama i u medijima. Pavlović je postao meta homofobnih napada pri čemu su takođe objavljivane i stare slike sa njegovog Instagram profila. `,
    `Aktivista Lazar Pavlović našao se na meti homofobnih uvreda nakon protesta`,
    `2023-05-28`,
    ``,
    `Civilni sektor`,
    `Medijski sektor`,
    `Prevare, pretnje i manipulacije`,
    `Ugrožavanje reputacije`,
    `Organizovani napadi na mrežama usmereni na ranjive zajednice (žene, lgbtq+, etničke manjine, izbeglice i migranti)`,
    `Diskriminacija i govor mržnje`,
    `Organizovani napadi na mrežama usmereni na ranjive zajednice (žene, lgbtq+, etničke manjine, izbeglice i migranti)`,
    `Diskriminacija i govor mržnje`,
    `Napadi koji se temelje na rodu i seksualnoj orijentaciji`,
    `Zadiranje u privatnost`,
    `Prikupljanje, manipulacija, diseminacija i zloupotreba ličnih podataka`,
    `Targetirani i organizovani napadi na zajednice`,
    `Organizovani napadi na mrežama usmereni na ranjive zajednice (žene, lgbtq+, etničke manjine, izbeglice i migranti)`,
    `https://twitter.com/dasezna/status/1663167547569582080`,
    `https://www.politika.rs/sr/clanak/555094/Ko-je-Lazar-Pavlovic-koji-je-nosio-majicu-lesinar-tata`,
    `https://twitter.com/DrugaSrbijaBis/status/1662702953554227200?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1662702953554227200%7Ctwgr%5E480e50488220ad2061f8085f9e56fb4eb2f42cc8%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fwww.alo.rs%2Fvesti%2Fpolitika%2F764869%2Fgej-i-opozicionar-po-potrebi-a-sad-postao-porodicni-covek-ko-je-lazar-pavlovic-i-sta-je-radio-na-protestu%2Fvest`,
    `https://archive.li/OGzKN`,
    `https://archive.li/bbU74`,
    `https://archive.li/61g5i`,
    ``,
    `prikupljanje, manipulacija, diseminacija i zloupotreba licnih podataka?`,
  ],
  [
    `Nekoliko dana nakon masovne pucnjave u osnovnoj školi "Vladislav Ribnikar" u Beogradu, na TikToku se pojavio video koji navodno pokazuje učenike te škole kako maltretiraju ubicu uz komentare da video prikazuje trenutke pre masakra ili da je ovo samo primer tretmana koji je ubica doživljavao u školi. Brzo je otkriveno da je video zapravo iz škole u Rusiji i da je objavljen pre nekoliko meseci te da ni na koji način nije povezan sa tragedijom. Uprkos ovim saznanjima, video je masovno cirkulisao po društvenoj mreži i i dalje se nalazi na vise naloga koji izražavaju simpatije prema ubici. `,
    `Lažni video vršnjačkog nasilja cirkulisao na TikToku nakon masovnog ubistva u osnovnoj školi`,
    `2023-05-06`,
    ``,
    `Građani`,
    `Nepoznato`,
    `Prevare, pretnje i manipulacije`,
    `Dezinformisanje javnosti`,
    `Manipulacija sadržaja`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://vm.tiktok.com/ZM22b3sJU/?t=2`,
    ``,
    ``,
    `https://archive.li/cZ9UV`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Udruženje građana Fruškać izgubilo je pred Višim sudom u Beogradu prvostepeni spor po tužbi zbog deljenja fotografije na kojoj su bili tagovani putem Instagram storija. Udruženje je presudom obavezano da isplati 115.000 dinara na ime naknade štete za autorska prava i sudskh troškova, i najavilo žalbu na presudu. `,
    `Presuda protiv udruženja građana zbog deljenja fotografije na Instagramu`,
    `2023-05-30`,
    ``,
    `Civilni sektor`,
    `Građani`,
    `Prevare, pretnje i manipulacije`,
    `Ograničavanje slobode izražavanja`,
    `Zloupotreba pravnih mehanizama`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.facebook.com/story.php?story_fbid=pfbid02TYFtgSgpHo1UEdZxwmWPvFD92DiXaTkf679Rf6guAVrVGUPvkfQYCw5m1SFzbQtxl&id=1008229337&mibextid=qC1gEa`,
    ``,
    ``,
    `(screenshot)`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Na Instagramu su otkrivena dva lažna profila koji ženama šalju eksplicitne poruke. Na Tviteru se javio broj žena koji je dobio poruke sa ovih profila i neke su utvrdile da su fotografije korišćene na nalozima skinute sa interneta. Profili Aleksandar Božić i Popović Vlada predstavljaju se kao da su sa Pravoslavno bogoslovskog fakulteta u Beogradu.`,
    `Otkriveni lažni profili koji uznemiravaju žene na Instagramu`,
    `2023-04-05`,
    ``,
    `Građani`,
    `Nepoznato`,
    `Prevare, pretnje i manipulacije`,
    `Ugrožavanje sigurnosti`,
    `Mobing na mrežama`,
    ``,
    ``,
    ``,
    ``,
    `Uznemiravanje`,
    `Mobing na mrežama`,
    ``,
    ``,
    `https://twitter.com/jasampicko_/status/1643712979412697088`,
    ``,
    ``,
    `https://archive.li/Op9ca`,
    `(screenshot 1&2)`,
    ``,
    ``,
    `ugrožavanje sigurnosti / uznemiravanje`,
  ],
  [
    `U utorak, 23. maja, nova serija anonimnih i lažnih dojava o postavljenim bombama pogodila je škole u Novom Sadu, Nišu, Kragujevcu, Kruševcu, Čačku i Gornjem Milanovcu. Prema podacima MUP-a tog dana je pristiglo čak 200 prijava o bombama. Policija je svaku dojavu proverila i utvrđeno je da su sve bile lažne. Takođe, dojave o bombama su stigle i na Vojno-medicinsku akademiju, Kliničko-bolnički centar Zvezdara, kao i Zoološki vrt u Beogradu. `,
    `Lažne dojave o bombama preko mejla`,
    `2023-05-17`,
    ``,
    `Građani`,
    `Nepoznato`,
    `Sajber incidenti`,
    `Onlajn prevare`,
    `Socijalni inženjering (fišing/vishing/smishing, lažno predstavljanje)`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.bbc.com/serbian/lat/svet-65619123`,
    ``,
    ``,
    `https://archive.li/eUAnx`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Sajt JUGpressa nedavno je bio izložen ozbiljnom napadu i pokušaju upada u njihov sistem, ali zahvaljujući brzoj reakciji njihovog tima za tehničku podršku, posledice su uspešno otklonjene. Ova medijska kuća već je ranije bila na udaru sličnih napada, što navodi na sumnju da je ovaj incident još jedan pokušaj vršenja pritiska zbog njihove objektivne, profesionalne i nepristrasne uređivačke politike. Sajt JUGpressa je bio još jednom pod tehničkim napadom 21. juna, i uspeli su da se oporave i posle ovog napada. `,
    `Sajt JUGpressa meta ozbiljnog napada`,
    `2023-05-15`,
    `2023-05-17`,
    `Medijski sektor`,
    `Nepoznato`,
    `Sajber incidenti`,
    `Onesposobljen servis`,
    `DoS/DDoS`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.facebook.com/ljiljana.stojanovic.1654/posts/pfbid02SyGkA7zyN5CcPTatfsi1U6FHN82LAhyeNcnh54TJ8YcRAnTAvPC1SWAiqVuJJQNYl`,
    `https://jugpress.com/sajt-regionalne-informativne-agencije-jugpress-ponovo-radi/`,
    `https://www.facebook.com/ljiljana.stojanovic.1654/posts/pfbid0R5yB6wSMisHip2dYfwkBg77RG1V8DDogZAt153a1VyXA2TbVdNXb7Mevt5Cou476l `,
    `https://archive.li/DobTO`,
    `https://archive.li/yWAfM`,
    `https://archive.li/uESSY`,
    ``,
    ``,
  ],
  [
    `Nacionalni CERT Republike Srbije upozorio je na novu fišing kampanju usmerenu na korisnike poštanskih usluga. Korisnicima se šalje lažna SMS poruka koja tvrdi da njihov paket nije mogao biti isporučen zbog navodno neplaćene carine, a poručuje im se da otvore link iz poruke koji vodi ka lažnoj stranici na kojoj se traži popunjavanje podataka o bankovnoj kartici. I time omogućava napadačima da preuzmu novac sa bankovnog računa korisnika.`,
    `Fišing kampanja koja targetira korisnike poštanskih usluga`,
    `2023-05-10`,
    ``,
    `Građani`,
    `Nepoznato`,
    `Sajber incidenti`,
    `Onlajn prevare`,
    `Lažni resursi (krivotvoreni sajt, mejl)`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.cert.rs/rs/obavestenje/1042-Fi%C5%A1ing-napadi-putem-SMS-poruka-na-korisnike-po%C5%A1tanskih-usluga.html`,
    ``,
    ``,
    `https://archive.li/HczV2`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Na Tviteru se pojavila fotografija pisma ostavke Ministarke Rudarstva i Energetike Dubravke Đedović. Ubrzo je otkriveno da je pismo fabrikovano i da ministarka nije podnela ostavku. Na dokumentu je falio potpis i pečat i korisnici su brzo ustanovili da je u pitanju lažna vest.`,
    `Na Tviteru objavljena lažna ostavka ministarke`,
    `2023-06-08`,
    ``,
    `Građani`,
    `Nepoznato`,
    `Prevare, pretnje i manipulacije`,
    `Dezinformisanje javnosti`,
    `Kreiranje i deljenje lažnih sadržaja`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/andrejic_bojan/status/1666594733622280192`,
    ``,
    ``,
    `https://archive.li/XjdYz`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `U jeku podrške broja glumaca i glumica protestima protiv nasilja koji traju nedeljama, na društvenim mrežama počeli su da cirkulišu sadržaji u kojima se objavljuje koliko novca ove javne ličnosti dobijaju od državnog operatera Telekom Srbija za snimanje serija i filmova u njihovoj produkciji. Ne zna se odakle su ove informacije potekle, ali su napadi na mrežama usledili nakon što su narodni poslanici u Skupštini čitali slične spiskove. `,
    `Glumci i glumice trpe organizovane napade na mrežama`,
    `2023-06-11`,
    ``,
    `Javne ličnosti`,
    `Nepoznato`,
    `Prevare, pretnje i manipulacije`,
    `Ugrožavanje sigurnosti`,
    `Prikupljanje, manipulacija, diseminacija i zloupotreba ličnih podataka`,
    `Ograničavanje slobode izražavanja`,
    `Verbalni napadi`,
    `Ugrožavanje sigurnosti`,
    `Mobing na mrežama`,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/PrijateljNaroda/status/1667978013093314565`,
    ``,
    ``,
    `https://archive.li/g1Pqz`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Član Predsedništva Srpske napredne stranke i Potpredsednica Narodne skupštine Sandra Božić je na Tviteru napala glumca Milana Marića dan nakon što je Marić govorio na protestu "Srbija protiv nasilja". Božić je prozvala glumca zbog takozvanih "antisrpskih" stavova i podelila video u kojem Marić čita iskaze žrtava i svedoka genocida u Srebrenici sa suđenja Radislavu Krstiću i Ratku Mladiću koji je nastao kao deo projekta Haškog suda. Marić je i ranije zbog ovog videa bio meta kritika, ali je nakon uključenja u proteste ponovo privukao pažnju javnosti. `,
    `Potpresednica Narodne skupštine targetirala glumca na Tviteru zbog podrške protestima`,
    `2023-06-10`,
    ``,
    `Javne ličnosti`,
    `Politički subjekt`,
    `Prevare, pretnje i manipulacije`,
    `Ugrožavanje reputacije`,
    `Verbalni napadi`,
    `Ograničavanje slobode izražavanja`,
    `Verbalni napadi`,
    `Ugrožavanje sigurnosti`,
    `Mobing na mrežama`,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/BozicSandra/status/1667316490964533248`,
    ``,
    ``,
    `https://archive.ph/8khkt`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Nakon što je podržala proteste, glumici Tamari Dragićević nedeljama su stizale mnogobrojne pretnje na Instragramu. U poslednjim porukama se glumici poručuje da se zna gde su joj deca otišla na izlet kao i kada imaju završne priredbe. Pretnje su prijavljene policiji. `,
    `Glumici i njenoj deci upućene pretnje na Instagramu`,
    `2023-06-10`,
    ``,
    `Javne ličnosti`,
    `Nepoznato`,
    `Prevare, pretnje i manipulacije`,
    `Ugrožavanje sigurnosti`,
    `Verbalni napadi`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.instagram.com/p/CtWNWWrsOH5/?igshid=MzRlODBiNWFlZA%3D%3D`,
    `https://n1info.rs/vesti/glumici-tamari-dragicevic-stigle-pretnje-zbog-podrske-protestu-spominju-i-decu/`,
    ``,
    `(screenshot)`,
    `https://archive.li/dtHTT`,
    ``,
    ``,
    ``,
  ],
  [
    `Nuklearnoj inžinjerki je zbog tvitova na nalogu pod pseudonimom "Mila Sila" uručen otkaz u Direktoratu za radijacionu i nuklearnu sigurnost i bezbednost. Tvitovi su sadržali kritike ponašanja visokih državnih funkcionera, a inženjerka je zbog tvitova i ranije bila targetirana disciplinskim merama na radnom mestu.`,
    `Nukleana inženjerka dobila otkaz zbog kritičkih tvitova o vlasti`,
    `2023-06-09`,
    ``,
    `Građani`,
    `Organi vlasti`,
    `Prevare, pretnje i manipulacije`,
    `Ograničavanje slobode izražavanja`,
    `Odmazda za iznete stavove`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.vreme.com/kolumna/slucaj-nuklearne-inzenjerke-otkaz-zbog-politicki-nepodobnih-tvitova/`,
    ``,
    ``,
    `https://archive.li/sM4nd`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Nezavisno pozorište "Reflektor teatar" je na Tviteru objavilo niz o 90-im godinama i ratovima na prostoru bivše SFRJ i pozvalo građane da podele šta znaju o mladosti svojih roditelja. U odgovorima na njihove tvitove je usledio veliki broj uvreda i pretnji upućenih teatru. `,
    `Pozorište na meti pretnji i uvreda na Tviteru`,
    `2023-06-13`,
    ``,
    `Civilni sektor`,
    `Građani`,
    `Prevare, pretnje i manipulacije`,
    `Ugrožavanje sigurnosti`,
    `Verbalni napadi`,
    `Ograničavanje slobode izražavanja`,
    `Verbalni napadi`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/reflektorteatar/status/1668588910253862913?t=eVkbT4EVW__tq_GJSNYfag&s=35`,
    ``,
    ``,
    `https://archive.li/kFEbD`,
    ``,
    ``,
    ``,
    `da li ovde još neka potkategorija treba?`,
  ],
  [
    `Sa sajta Radio-televizije Vojvodine (RTV) obrisana je vest o odluci Upravog odbora te institucije da umesto izbora novog generalnog direktora imenuje novog vršioca dužnosti te funkcije. Vest je takođe obrisana sa drugih vojvođanskih portala poput Dnevnika i Vojvodina uživo.`,
    `Vest o odluci Upravnog odbora RTV brisana sa sajtova medija`,
    `2023-06-21`,
    ``,
    `Građani`,
    `Medijski sektor`,
    `Prevare, pretnje i manipulacije`,
    `Autocenzura`,
    `Uklanjanje sadržaja`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.cenzolovka.rs/drzava-i-mediji/skandal-oko-izbora-direktora-rtv-nekom-se-odluka-upravnog-odbora-nije-dopala-vest-izbrisana-sa-nekoliko-portala/`,
    ``,
    ``,
    `https://archive.li/aLsB5`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Popularni jutjuber objavio je lajvstrim u kojem je listao Tinder profile devojaka komentarišući ih.  On je u videu iznosio uvrede i neumesne šale na račun trans devojke koja je prijavila zlostavljanje organizaciji Da se zna. `,
    `Popularni jutjuber vređao trans osobu u svom lajvstrimu`,
    `2023-06-21`,
    ``,
    `Građani`,
    `Javne ličnosti`,
    `Prevare, pretnje i manipulacije`,
    `Ugrožavanje reputacije`,
    `Organizovani napadi na mrežama usmereni na ranjive zajednice (žene, lgbtq+, etničke manjine, izbeglice i migranti)`,
    `Diskriminacija i govor mržnje`,
    `Organizovani napadi na mrežama usmereni na ranjive zajednice (žene, lgbtq+, etničke manjine, izbeglice i migranti)`,
    `Diskriminacija i govor mržnje`,
    `Napadi koji se temelje na rodu i seksualnoj orijentaciji`,
    `Zadiranje u privatnost`,
    `Prikupljanje, manipulacija, diseminacija i zloupotreba ličnih podataka`,
    `Targetirani i organizovani napadi na zajednice`,
    `Organizovani napadi na mrežama usmereni na ranjive zajednice (žene, lgbtq+, etničke manjine, izbeglice i migranti)`,
    `https://www.instagram.com/p/CttgvTiMaEa/?igshid=MTc4MmM1YmI2Ng%3D%3D`,
    ``,
    ``,
    `(screenshot)`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Narodna banka Srbije upozorava građane da budu oprezni ukoliko dobiju SMS poruke sa nepoznatih brojeva telefona, posebno onih sa pozivnim brojem +33. Pošiljalac se lažno predstavlja kao pružalac usluga za Netflliks, Pošta Srbije, DHL i slično, ali se radi o prevari. Veb stranice koje su linkovne u SMS poruci su lažne.`,
    `NBS upozorila na prevare putem SMS-a`,
    `2023-06-27`,
    ``,
    `Građani`,
    `Nepoznato`,
    `Sajber incidenti`,
    `Onlajn prevare`,
    `Lažni resursi (krivotvoreni sajt, mejl)`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.021.rs/story/Info/Srbija/345058/NBS-upozorila-na-SMS-prevaru-Obratite-paznju-na-nepoznate-brojeve.html`,
    ``,
    ``,
    `https://archive.li/li9Ff`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Privatni snimak koji je folk pevačica Ana Nikolić poslala Saši Mirković, direktoru Hype televizije, kojem se direktno obraća u videu, objavljen je na društvenim profilima televizijske stanice bez njene saglasnosti. Snimak je podeljen sa opisom u kojem tim televizije implicira da je pevačica, kojoj se očigledno vidi da nije dobro, koristila razne suspstance, i jasno je da je video bio namenjen određenoj osobi i da nije bio za deljenje. Video je brzo počeo da se širi društvenim mrežama i objavljivan je od strane raznih drugih naloga. `,
    `Privatni snimak pevačice okačen na mreže bez saglasnosti`,
    `2023-07-01`,
    ``,
    `Javne ličnosti`,
    `Javne ličnosti`,
    `Prevare, pretnje i manipulacije`,
    `Ugrožavanje reputacije`,
    `Distribucija sadržaja bez saglasnosti`,
    ``,
    ``,
    ``,
    ``,
    `Zadiranje u privatnost`,
    `Distribucija sadržaja (uključujući i osvetničku pornografiju) bez saglasnosti`,
    `Zadiranje u privatnost`,
    `Prikupljanje, manipulacija, diseminacija i zloupotreba ličnih podataka`,
    `https://twitter.com/Sivaeminencija2/status/1675091170932801536?s=20`,
    `https://twitter.com/Tajniznak26/status/1675093695643648003`,
    ``,
    `(screenshot 1&2)`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Sajt Južnih vesti tokom 3. Jula pretrpeo je ozbiljan DDoS napad na njihov sajt. Na sreću posledice su uspešno otklonjene. O napadu su čitaoce obavetili preko Tviter naloga. `,
    `Sajt regionalnog medija pod tehničkim napadom`,
    `2023-07-03`,
    `2023-07-03`,
    `Medijski sektor`,
    `Nepoznato`,
    `Sajber incidenti`,
    `Onesposobljen servis`,
    `DoS/DDoS`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/juznevesti/status/1675874913415049218?t=PgKPl5roQ26kLzBzFL32Kg&s=09`,
    ``,
    ``,
    `(screenshot-juznevesti)`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Na objavama na društvenim mrežama koje je povodom ubistva trans devojke Noe Milivojev objavila organizacija Da se zna objavljeni su brojni transfobični komentari. U nekim od ovih komentara izvršeno je dednejmovanje Noe, odnosno navođenje njenog imena pre tranzicije.`,
    `Transfobija i dednejmovanje ubijene trans devojke na društvenim mrežama`,
    `2023-07-06`,
    ``,
    `Građani`,
    `Građani`,
    `Prevare, pretnje i manipulacije`,
    `Diskriminacija i govor mržnje`,
    `Napadi koji se temelje na rodu i seksualnoj orijentaciji`,
    ``,
    ``,
    ``,
    ``,
    `Zadiranje u privatnost`,
    `Prikupljanje, manipulacija, diseminacija i zloupotreba ličnih podataka`,
    ``,
    ``,
    `https://twitter.com/dasezna/status/1676979327173271552?t=6fy-eoIWOgGolV_rQ_k6tA&s=35`,
    ``,
    ``,
    `https://archive.li/KRfCx`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Tviter korisnik @protivdictature objavio je spisak naloga koji su navodno botovi Srpske napredne stranke. Spisak sadrži imena, prezimena i mesto prebivalista osobe koja stoji iza naloga kao i sam nalog koji je u pitanju. I dalje nije jasno odakle je spisak potekao, nalog koji je objavio tvrdi da ga je platio i dobio od Sprske napredne stranke. U danima nakon što je spisak objavljen, drugi korisnici Tvitera tvrdili su da su pronašli svoje poznanike i članove porodica na spiskovima, neki su objavljivali informacije o radnim mestima nekih i u nekim slučajevima je navedeno da su ljudi sa spiskova pretrpeli fizičko nasilje.`,
    `Spisak botova SNS objavljen na Tviteru, izvor nepoznat`,
    `2023-07-06`,
    ``,
    `Masovna povreda`,
    `Privatno (fizičko) lice`,
    `Privatnost i zaštita podataka`,
    `Objavljivanje podataka`,
    `Objavljivanje na društvenoj mreži, blogu, u čet aplikaciji`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/protivdictature/status/1677054817649213440?s=46`,
    ``,
    ``,
    `https://archive.li/BWQHF`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Veliki broj slika i ličnih podataka ljudi čija imena su se nalašla na spisku botova koji je objavljen 06. jula na Tviteru je u prethodnim danima bio izložen raznim verbalnim napadima i pretnjama na mrežama. Ženske osobe sa ovih spiskova su se pored opštih napada našle i na meti mizoginih i uvredljivih komentara koji su rodno zasnovani više nego išta. `,
    `Žene sa spiska botova na mrežama našle su se na meti mizoginih komentara i pretnji `,
    `2023-07-10`,
    ``,
    `Građani`,
    `Građani`,
    `Prevare, pretnje i manipulacije`,
    `Diskriminacija i govor mržnje`,
    `Prikupljanje, manipulacija, diseminacija i zloupotreba ličnih podataka`,
    `Diskriminacija i govor mržnje`,
    `Napadi koji se temelje na rodu i seksualnoj orijentaciji`,
    ``,
    ``,
    `Uznemiravanje`,
    `Direktne pretnje nasiljem uključujući pretnje koje su seksualne ili fizičke prirode`,
    `Zadiranje u privatnost`,
    `Prikupljanje, manipulacija, diseminacija i zloupotreba ličnih podataka`,
    `https://twitter.com/MisoIlic032/status/1678506098171555840?s=20`,
    `https://twitter.com/kaldrma70/status/1678479739944681474?s=20`,
    ``,
    `https://archive.li/IqSmY`,
    `https://archive.ph/fd0vH`,
    ``,
    ``,
    ``,
  ],
  [
    `Istok Pavlović objavio je na svom TikToku video u kojem je koristio sliku iz intimnog videa pevačice Severine Vučković iz 2004. godine kako bi demonstrirao mogućnosti novih AI alata u fotošopu. Nakon što je video naišao na negodovanje na mrežama, Pavlović je objavio objašnjenje gde se nije izvinio, već pokušao da opravda korišćenje fotografije. `,
    `Kreator iskoristio intimni snimak pevačice bez saglasnosti za promociju svog sadržaja`,
    `2023-07-09`,
    ``,
    `Javne ličnosti`,
    `Javne ličnosti`,
    `Prevare, pretnje i manipulacije`,
    `Ugrožavanje reputacije`,
    `Distribucija intimnih sadržaja bez saglasnosti`,
    ``,
    ``,
    ``,
    ``,
    `Zadiranje u privatnost`,
    `Distribucija sadržaja (uključujući i osvetničku pornografiju) bez saglasnosti`,
    ``,
    ``,
    `https://twitter.com/preputiumpenis/status/1678143335226044420?s=46`,
    ``,
    ``,
    `https://archive.ph/mg5Ux`,
    ``,
    ``,
    ``,
    ``,
  ],
];
