export const newEnCases = [
  [
    `N1 journalist Žaklina Tatalović received threatening messages through social media.  Tatalović received death threats and insults about her work from the profiles “Alma Begović” and “Sabo Zoltan”. She reported the threats to the police. The journalists’ union UNS reminds that threats to journalists are unacceptable, and the authors of such content must be held responsible.`,
    `Serbian Journalist Threatened on Social Media`,
    `2023-03-29`,
    ``,
    `Media sector`,
    `Unknown`,
    `Fraud, threats and manipulations`,
    `Endangering security`,
    `Direct threats of violence, including threats of a sexual or physical nature`,
    `Limiting freedom of expression`,
    `Verbal attacks`,
    ``,
    ``,
    `Harassment`,
    `Direct threats of violence, including threats of a sexual or physical nature`,
    ``,
    ``,
    `https://www.uns.org.rs/sr/saopstenja/143328/uns-tuzilastvo-za-vtk-da-pronadje-ko-preti-smrcu-zaklini-tatalovic.html`,
    ``,
    ``,
    `https://archive.li/DZb2R`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Mayor Aleksandar Šapić has sued BIRN Serbia, the editor-in- chief Milorad Ivanović, and journalists Jelena Veljković, Aleksandar Đorđević, and Radmil Marković for allegedly spreading falsehoods about his villa in Trieste and the legalization of building on Bežanijska  Kosa. The lawsuits were filed for defamation and violations of honour, reputation, and human dignity. Šapić claims that the information caused immense harm and damage to his honour and reputation.`,
    `BIRN Serbia Sued by Mayor for Damaging Reputation`,
    `2023-03-29`,
    ``,
    `Media sector`,
    `Political subject`,
    `Fraud, threats and manipulations`,
    `Limiting freedom of expression`,
    `Abuse of legal mechanisms`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://birn.rs/sapic-tuzio-birn/`,
    ``,
    ``,
    `https://archive.li/jQpph`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `The website and web server of the Business Registers Agency were targeted by Distributed Denial-of-Service DDoS attacks. The agency successfully defended the system on Monday and enabled access to all of its web services, with occasional interruptions, and the system is now operating smoothly. The agency reported the DDoS attacks to the National Center for the Prevention of Security Risks in ICT Systems, National CERT, and the Ministry of Information and Telecommunications.`,
    `Serbia Business Agency Website Targeted by Technical Attack`,
    `2023-03-27`,
    ``,
    `Public sector`,
    `Unknown`,
    `Cyber incidents`,
    `Disabled services`,
    `DoS/DDoS`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.slobodnaevropa.org/a/sajt-apr-sajber-napad/32336304.html`,
    `https://apr.gov.rs/vesti.2428.html?newsId=3618`,
    ``,
    `https://archive.ph/F6C5c`,
    `https://archive.ph/dOhYQ`,
    ``,
    ``,
    ``,
  ],
  [
    `The extremist “Our Conservative Movement” sent a threat to the official email address of NDNV (Independent Journalists' Association of Vojvodina) accusing the organization and the Autonomija portal of being “foreign mercenaries” who are waging a “media war against Russia and Serbia” and “promoting Ukrainian neo-Nazism”. The email specifically targeted NDNV’s program director Dinko Gruhonjić and Autonomija columnist Teofil Pančić. NDNV is calling on the authorities to investigate the organization that targets domestic media and organizations in favor of another state.`,
    `Serbian Media and Journalists Threatened via Email`,
    `2023-03-15`,
    ``,
    `Media sector`,
    `Individual`,
    `Fraud, threats and manipulations`,
    `Endangering security`,
    `Verbal attacks`,
    `Limiting freedom of expression`,
    `Verbal attacks`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://ndnv.org/2023/03/16/ndnv-na-meti-ekstremista-institucije-da-sprece-fasizaciju-drustva/`,
    ``,
    ``,
    `https://archive.li/Xo0WR`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `A phishing campaign with a fake e-invoice, logo and name of Yettel company has been circulating on the internet in Serbia Although the e-invoice looked almost identical to Yettel’s invoices, users were warned to pay attention to the domain.`,
    `Serbia Phishing Campaign Involves Fake e-invoice`,
    `2023-03-20`,
    ``,
    `The public`,
    `Unknown`,
    `Cyber incidents`,
    `Online scams`,
    `Social engineering (phishing/vishing/smishing, impersonation)`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.linkedin.com/posts/dragan-jovanovi%C4%87-a4481627_ponovo-problemati%C4%8Dna-phishing-aktivnost-na-activity-7039563333691138048-fCro/`,
    ``,
    ``,
    `https://archive.ph/YZWHV`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Stevan Dojčinović, an investigative journalist and editor- in-chief of KRIK, spoke about the life paths of criminals and the recruitment of young men into fan groups on the Snaga uma podcast. Following this, a comment appeared on TikTok suggesting that Dojčinović should be killed. This public death threat was reported to the Special Prosecution Office for High-Tech Crime.`,
    `Serbian Journalist Threatened with Death on Tik Tok`,
    `2023-03-07`,
    ``,
    `Media sector`,
    `Unknown`,
    `Fraud, threats and manipulations`,
    `Endangering security`,
    `Direct threats of violence, including threats of a sexual or physical nature`,
    `Limiting freedom of expression`,
    `Verbal attacks`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://nova.rs/vesti/drustvo/stevan-dojcinovic-dobio-pretnje-ubistvom-nakon-gostovanja-na-nova-rs-slucaj-prijavljen/`,
    ``,
    ``,
    `https://archive.li/PGdDA`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Šaip Kamberi, a Bosniak member of the Serbian parliament and head of the Jedinstvena dolina i SDA Sandžak parliamentary group, received death threats via Facebook from a person who introduced himself as Danijel Milković`,
    `Serbian MP Threatened on Facebook`,
    `2023-02-25`,
    ``,
    `Political subject`,
    `Individual`,
    `Fraud, threats and manipulations`,
    `Endangering security`,
    `Collection, manipulation, dissemination and misuse of personal data`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://n1info.rs/vesti/kamberi-dobio-pretnje-smrcu-nikad-neces-znati-kada-dolazim-po-tvoju-glavu/`,
    ``,
    ``,
    `https://archive.ph/YMBE8`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `A fake account of the politician and diplomat Milan St Protić has appeared on Twitter. Protić does not have an account on Twitter.`,
    `Serbian Politician and Diplomat Impersonated on Twitter`,
    `2023-02-11`,
    ``,
    `Public figures`,
    `Unknown`,
    `Fraud, threats and manipulations`,
    `Character assassination`,
    `Creating fake content and accounts`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/strani_placenik/status/1624404461572456453`,
    ``,
    ``,
    `https://archive.ph/YGeSs`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `BIRN Serbia found itself before the High Court in Belgrade after the owner of the company Jovanjica filed a lawsuit against BIRN claiming that untruths were published about him. BIRN Serbia believes the lawsuit represents an attempt to intimidate the media so that they do not write about certain topics or personalities.`,
    `Private Lawsuit Filed by Company Boss Against BIRN Serbia`,
    `2023-02-13`,
    ``,
    `Media sector`,
    `Political subject`,
    `Fraud, threats and manipulations`,
    `Limiting freedom of expression`,
    `Abuse of legal mechanisms`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://birn.rs/predrag-koluvija-tuzio-birn/`,
    ``,
    ``,
    `https://archive.ph/dP7xK`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Portal Nova.rs’ journalist Pero Jovović received threats via Twitter. He reported the case to the Prosecutor's Office for High-Tech Crime. The Association of Journalists of Serbia condemned the threats.`,
    `Serbian Journalist Threatened on Twitter`,
    `2023-02-09`,
    ``,
    `Media sector`,
    `Individual`,
    `Fraud, threats and manipulations`,
    `Endangering security`,
    `Direct threats of violence, including threats of a sexual or physical nature`,
    `Discrimination and hate speech`,
    `Attacks based on gender and sexual characteristics`,
    ``,
    ``,
    `Harassment`,
    `Attacks based on gender and sexual characteristics`,
    `Harassment`,
    `Direct threats of violence, including threats of a sexual or physical nature`,
    `https://www.cenzolovka.rs/pritisci-i-napadi/jezive-pretnje-novinaru-peru-jovovicu-treba-ti-staviti-pistolj-na-celo-i-opaliti-metak-bez-trunke-savesti/`,
    ``,
    ``,
    `https://archive.is/5mOG7`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Insults and threats were sent to the Instagram account of the journalist of the Radio 021, after she published an article about the studios at the Petrovaradin fortress, which, as stated in the article, are being used illegally.`,
    `Serbian Female Journalist Threatened on Instagram`,
    `2023-01-31`,
    ``,
    `Media sector`,
    `Individual`,
    `Fraud, threats and manipulations`,
    `Endangering security`,
    `Collection, manipulation, dissemination and misuse of personal data`,
    `Limiting freedom of expression`,
    `Verbal attacks`,
    ``,
    ``,
    `Harassment`,
    `Direct threats of violence, including threats of a sexual or physical nature`,
    ``,
    ``,
    `https://nuns.rs/nuns-procesuirati-pretnje-novinarki-gorici-nikolin/`,
    ``,
    ``,
    `https://archive.li/I4qI0`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Portal Danas published an interview with a non-existent person. The fake account for Daniel Smith on Twitter aimed to spread various propaganda content. After the text was published on the portal, Daniel Smith’s account was deleted.`,
    `Portal Danas Published Interview with Non-existent Expert`,
    `2023-02-05`,
    ``,
    `The public`,
    `Media sector`,
    `Fraud, threats and manipulations`,
    `Public misinformation`,
    `Creating and sharing fake content`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/frankblack2000/status/1621934449649745921?s=12&t=Z8pmNXycdRDEko4E2Z0cLQ`,
    `https://www.danas.rs/dijalog/licni-stavovi/sta-smo-naucili-iz-slucaja-daniel-smith/`,
    ``,
    `https://web.archive.org/web/20230206102011/https://twitter.com/frankblack2000/status/1621934449649745921?s=12&t=Z8pmNXycdRDEko4E2Z0cLQ`,
    `https://archive.li/oqYH3`,
    ``,
    ``,
    ``,
  ],
  [
    `Citizens received false malicious messages at the Stara Pazova Health Center and the My doctor portal as a part of a phishing campaign.`,
    `Email address of Health Centre in Serbia Abused`,
    `2023-01-25`,
    ``,
    `The public`,
    `Unknown`,
    `Cyber incidents`,
    `Online scams`,
    `Social engineering (phishing/vishing/smishing, impersonation)`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/ivanmarkovicsec/status/1618269721346068480`,
    ``,
    ``,
    `https://archive.ph/bk6RS`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Petar Đurić, President of the citizens’ association, was detained after posting a Tweet criticizing President Vucic. He was taken into custody by the Service for Combating Organized Crime SBPOK and released after questioning.`,
    `Serbian Activist Detained for Tweet About the President`,
    `2023-01-16`,
    ``,
    `Civil society`,
    `Authority figures`,
    `Fraud, threats and manipulations`,
    `Limiting freedom of expression`,
    `Abuse of legal mechanisms`,
    `Limiting freedom of expression`,
    `Retaliation`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.danas.rs/vesti/politika/petar-djuric-priveden-u-sbpok-advokat-stojkovic-tvrdi-da-mu-nisu-dozvolili-da-ga-vidi/`,
    ``,
    ``,
    `https://archive.ph/TaEN6`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `The co-president of the Zajedno party, Biljana Stojković, reported receiving an alarming threat on Twitter and reported the case to the police.`,
    `Serbian Female Politician Threatened on Twitter `,
    `2023-01-16`,
    ``,
    `Political subject`,
    `Unknown`,
    `Fraud, threats and manipulations`,
    `Endangering security`,
    `Direct threats of violence, including threats of a sexual or physical nature`,
    ``,
    ``,
    ``,
    ``,
    `Harassment`,
    `Direct threats of violence, including threats of a sexual or physical nature`,
    ``,
    ``,
    `https://n1info.rs/vesti/biljana-stojkovic-prijavila-policiji-pretnju-smrcu/`,
    ``,
    ``,
    `https://archive.ph/WC8nD`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Details of a phishing campaign that abuses the logo of the Post of Serbia were published on the Twitter profile of @ivanmarkovicsec. Messages are circulating on Viber. As stated, the domain vaxvjhjxd[.]cyou was purchased through a registry in China.`,
    `Phishing Campaign Abuses Serbian Post`,
    `2023-01-11`,
    ``,
    `The public`,
    `Unknown`,
    `Cyber incidents`,
    `Online scams`,
    `Social engineering (phishing/vishing/smishing, impersonation)`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/ivanmarkovicsec/status/1613242320253747201?t=fEa4AlhWJt-mU2VjaLfEhg&s=35`,
    ``,
    ``,
    `https://archive.li/BRcy3`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Nenad Paunović, a journalist from Pirot, was questioned by police with one other person after trying to film an accident scene with a drone on the day it was planned to raise a damaged tank on the railway. After four hours in detention, they were released.`,
    `Serbian journalist Detained for Filming Incident`,
    `2023-01-11`,
    ``,
    `Media sector`,
    `Authority figures`,
    `Fraud, threats and manipulations`,
    `Limiting freedom of expression`,
    `Abuse of legal mechanisms`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.cenzolovka.rs/pritisci-i-napadi/novinar-iz-pirota-povodom-privodjenja-zbog-snimanja-akcidenta-ne-mogu-da-mi-oproste-ministarku-i-mrtvog-turcina-koga-sam-nasao/`,
    ``,
    ``,
    `https://archive.li/CM9fd`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `There is information about attacks on the websites of state institutions, specifically the army, Defence Ministry, Foreign Ministry, MUP and President Aleksandar Vučić (vucic.rs) on social networks and in the media.`,
    `DDoS Attacks on Websites of Serbian Govt Ministries Reported`,
    `2023-01-06`,
    ``,
    `Public sector`,
    `Unknown`,
    `Cyber incidents`,
    `Disabled services`,
    `DoS/DDoS`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/ivanmarkovicsec/status/1610957828583219200?t=9h-ODE5wMC-fufFIZ-SicQ&s=35`,
    `https://twitter.com/ivanmarkovicsec/status/1611034259757613057?t=_lVNfVsSDlZESTlofIO9_g&s=35`,
    `https://www.slobodnaevropa.org/a/srbija-napadi-anonymous-institucije-sajtovi-serveri/32215930.html`,
    `https://archive.ph/IPGEj`,
    `https://archive.ph/M0kG5`,
    `https://archive.li/L2v44`,
    ``,
    ``,
  ],
  [
    `The company Yettel has informed citizens that a fake prize game is circulating on websites on the Internet. A malicious pop- up window was recorded on the site for converting YouTube videos to mp3 format. Apparently, after completing the survey, they receive valuable prizes.`,
    `Yettel Warns of False Prize Game Scam`,
    `2023-02-27`,
    ``,
    `The public`,
    `Unknown`,
    `Cyber incidents`,
    `Online scams`,
    `Social engineering (phishing/vishing/smishing, impersonation)`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.linkedin.com/feed/update/urn:li:activity:7036256371142500352/`,
    ``,
    ``,
    `https://archive.li/mYzf9`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `At the beginning of the year, there was a phishing campaign targeting SBB users via email, where users received fake emails informing them of an alleged problem with renewing services and directing them to the fake page http://eunet.co.rs.`,
    `Phishing Campaign Targets SBB users in Serbia`,
    `2023-01-03`,
    ``,
    `The public`,
    `Unknown`,
    `Cyber incidents`,
    `Online scams`,
    `Social engineering (phishing/vishing/smishing, impersonation)`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/ivanmarkovicsec/status/1610227799373086721?t=gVpNtg_P-fZqlMRqfd3Auw&s=35`,
    ``,
    ``,
    `https://archive.li/34WlP`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Days after a mass school shooting in Belgrade, footage started circulating on TikTok of alleged footage of the massacre from within the school. The video was quickly discovered to be from a different school shooting a couple of years back in the United States.`,
    `Fake footage of Belgrade school shooting circulated on social media`,
    `2023-05-06`,
    ``,
    `The public`,
    `Unknown`,
    `Fraud, threats and manipulations`,
    `Public misinformation`,
    `Content manipulation`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/mina_vrbaski/status/1654610887741784064`,
    ``,
    ``,
    `https://archive.li/ckfyy`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Daily newspaper Danas' journalist Nikola Krstić received numerous threats of violence on social networks after he wrote an article about the statement of the patriarch of the Serbian Orthodox Church, Porfirije. In the text, Krstić commented on the insulting statement that the head of the Serbian Orthodox Church made in relation to women in Serbia.`,
    `Journalist threatened over article about the patriarch`,
    `2023-05-18`,
    ``,
    `Media sector`,
    `Individual`,
    `Fraud, threats and manipulations`,
    `Endangering security`,
    `Direct threats of violence, including threats of a sexual or physical nature`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://kossev.info/safejournalist-zahteva-da-se-pronadju-osobe-koje-su-pretile-novinaru-lista-danas-nakon-teksta-o-patrijarhu-spc/`,
    `https://twitter.com/krkela_krle/status/1659113155413286912?s=20`,
    ``,
    `https://archive.li/yD8L3`,
    `https://archive.li/9RsDz`,
    ``,
    ``,
    ``,
  ],
  [
    `The investigative portal KRIK was convicted by a first-instance verdict of the High Court in Belgrade for publishing an article about who filed lawsuits against the media house. Three members of the police, who have already filed lawsuits and are mentioned in the text, sued KRIK again. The media is already obliged to pay almost 3,200 euros in compensation for suffering mental pain by the first-instance court decision, as well as to delete parts of the text in which members of the police are mentioned. KRIK announced that it will appeal the verdict.`,
    `Investigative journalism portal sentenced for publishing the names of the plaintiffs who sued them`,
    `2023-05-18`,
    ``,
    `Media sector`,
    `Authority figures`,
    `Fraud, threats and manipulations`,
    `Limiting freedom of expression`,
    `Abuse of legal mechanisms`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.krik.rs/krik-osudjen-jer-je-objavio-ko-je-tuzio-redakciju-presudu-doneo-sudija-keranovic-poznat-po-procesu-protiv-nin-a/`,
    ``,
    ``,
    `https://archive.li/LcUKR`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `The tabloid portal Republika sensationally reported on the funeral of those killed in the massacre in the vicinity of Mladenovac that took place on May 4, thus violating the journalistic code and retraumatizing the families of the victims. The Independent Association of Journalists of Serbia called on journalists to respect the privacy, dignity and integrity of the people they write about, especially when it comes to tragedies.`,
    `Portal Republika infringed on the privacy of the families of massacre victims`,
    `2023-05-09`,
    ``,
    `Individual casualty`,
    `Responsible person from the media sector`,
    `Privacy and data protection`,
    `Disclosure of data`,
    `Publication in the media`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://nuns.rs/nuns-portal-republika-da-postuje-kodeks-i-prava-na-privatnost-porodica-zrtava/`,
    ``,
    ``,
    `https://archive.li/99uCd`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `In the days following the mass murders in Belgrade elementary school "Vladislav Ribnikar", numerous misinformation related to the event was published on media websites in Serbia and the region as well as on social networks. Among other things, incorrect information was conveyed that the wounded teacher also died, that vaccinated citizens could not be blood donors and that N1 television demanded the release of the suspect.`,
    `Mass disinformation circulates about school shooting in Belgrade`,
    `2023-05-08`,
    ``,
    `The public`,
    `Media sector`,
    `Fraud, threats and manipulations`,
    `Public misinformation`,
    `Creating and sharing fake content`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.cenzolovka.rs/mediologija/dezinformacije-o-masakru-u-skoli-vladislav-ribnikar/`,
    ``,
    ``,
    `https://archive.li/9lkDY`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Serbian Progressive Party MP Staša Stojanović verbally attacked the deputy president of the Democratic Party and opposition MP Dragana Rakić on Twitter after Rakić shared a video showing Stojanović provoking her in the Assembly in response to a protest by the opposition at yesterday's session.`,
    `Ruling party MP insults opposition MP on Twitter`,
    `2023-05-25`,
    ``,
    `Political subject`,
    `Political subject`,
    `Fraud, threats and manipulations`,
    `Discrimination and hate speech`,
    `Verbal attacks`,
    ``,
    ``,
    ``,
    ``,
    `Harassment`,
    `Attacks based on gender and sexual characteristics`,
    ``,
    ``,
    `https://twitter.com/stasasns/status/1661776299877183490?s=46`,
    ``,
    ``,
    `https://archive.li/14iY8`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `On famous Serbian singer Šaban Šaulić's Instagram account, an invitation was published for a rally in support of President Aleksandar Vučić and the Serbian Progressive Party in Belgrade, scheduled for May 26. A large number of public figures shared the invitation on their accounts, but Šaulić was the only one who did so posthumously.`,
    `Deceased Serbian singer posted on Instagram to invite people to SNS meeting`,
    `2023-05-24`,
    ``,
    `The public`,
    `Political subject`,
    `Fraud, threats and manipulations`,
    `Public misinformation`,
    `Content manipulation`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/NikolaLaki3/status/1661340279469744128`,
    `https://direktno.rs/vesti/drustvo-i-ekonomija/472153/saban-saulic-miting-vucic.html`,
    ``,
    `https://archive.li/hhfb8`,
    `https://archive.li/8Dd2e`,
    ``,
    ``,
    ``,
  ],
  [
    `Olja Bećković, author and host of the TV show “Utisak nedelje,” received disturbing text messages on her personal phone from Sime Spasić, the president of the Association of Families of Kidnapped, Murdered and Missing Persons from Kosovo and Metohija.`,
    `Serbian TV Show Host Received Threats on Personal Number`,
    `2023-04-10`,
    ``,
    `Media sector`,
    `Political subject`,
    `Fraud, threats and manipulations`,
    `Endangering security`,
    `Direct threats of violence, including threats of a sexual or physical nature`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.danas.rs/vesti/drustvo/nisam-prijavila-ovo-nije-prvi-put-simo-spasic-pretio-i-olji-beckovic/`,
    ``,
    ``,
    `https://archive.ph/j4DkG`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `TV host Ivan Ivanović received explicit threats on his private number from Simo Spasić, president of the Association of Families of Kidnapped, Murdered and Missing Persons from Kosovo and Metohija. Spasić also made serious misogynistic and explicit threats to members of Ivanović's family. Spasić was arrested on June 19th. for endangering the hosts security.`,
    `TV host receives serious threats via SMS`,
    `2023-04-09`,
    ``,
    `Public figures`,
    `Political subject`,
    `Fraud, threats and manipulations`,
    `Endangering security`,
    `Direct threats of violence, including threats of a sexual or physical nature`,
    ``,
    ``,
    ``,
    ``,
    `Harassment`,
    `Direct threats of violence, including threats of a sexual or physical nature`,
    ``,
    ``,
    `https://twitter.com/veceivan/status/1645172873055592448?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1645172873055592448%7Ctwgr%5E100438cb9068f82acf9c09eea99539560e35709a%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fwww.danas.rs%2Fvesti%2Fdrustvo%2Fivanu-ivanovicu-i-njegovoj-porodici-vulgarne-pretnje-uputio-simo-spasic%2F`,
    `https://n1info.rs/vesti/uhapsen-simo-spasic-zbog-ugrozavanja-sigurnosti-ivana-ivanovica/`,
    ``,
    `https://archive.li/9viel`,
    `https://archive.li/M8egA`,
    ``,
    ``,
    ``,
  ],
  [
    `Singer Vlado Georgijev threatened journalists from Nova.rs who published an article about his company Danube Cargo, which he opened in 2020 and deals with the transportation of cargo on inland waterways. They published the company’s history and financial reports.`,
    `Journalists Threatened Over Article on Cargo Company`,
    `2023-04-10`,
    ``,
    `Media sector`,
    `Public figures`,
    `Fraud, threats and manipulations`,
    `Endangering security`,
    `Direct threats of violence, including threats of a sexual or physical nature`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://nova.rs/zabava/showbiz/trazicu-te-po-gradu-skandalozne-pretnje-vlada-georgieva-redakciji-nova-rs-nakon-pitanja-o-njegovom-biznisu/`,
    ``,
    ``,
    `https://archive.ph/SJ0nA`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Večernje novosti, a Serbian media outlet with a predominantly anti-Western editorial policy, deleted an article about the US ambassador to Serbia, Christopher Hill, from its website. The article has become unavailable although internet search and news aggregators show it was published. In addition to details from Hill’s life, the article contained negative remarks about his attitude towards Serbia and the Serbian people.`,
    `Serbian News Portal Deletes Article on US Ambassador`,
    `2023-04-04`,
    ``,
    `The public`,
    `Political subject`,
    `Fraud, threats and manipulations`,
    `Self censorship`,
    `Content removal`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://n1info.rs/vesti/vecernje-novosti-objavile-pa-obrisale-pamflet-o-ambasadoru-kristoferu-hilu/`,
    `https://time.rs/c/179ed6dde6/diplomata-koji-ni-je-voleo-srbiju-mrznja-prema-srbima-pod-velom-maslinove-grancice.html`,
    ``,
    `https://archive.li/CI6m6`,
    `https://archive.li/6w4Pe`,
    ``,
    ``,
    ``,
  ],
  [
    `Folk singer Jelena Karleuša posted on her Instagram account demanding that MP Marinika Tepić declare her nationality, stating that if she does not identify as a Serb, she has no right to participate in protests and criticize the government because she is "ideologically" not a part of the Serbian people. The singer previously publicly supported President Vučić and criticized performers, primarily actresses and actors, for expressing negative attitudes towards the government and participating in the "Serbia against violence" anti-govenrment protests.`,
    `Singer Jelena Karleuša insulted MP Marinika Tepić on ethnic and national grounds`,
    `2023-05-28`,
    ``,
    `Political subject`,
    `Public figures`,
    `Fraud, threats and manipulations`,
    `Discrimination and hate speech`,
    `Attacks based on racial, religious, national or ethnic affiliation`,
    `Character assassination`,
    `Verbal attacks`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/amfibolije/status/1662834561221554181?s=46`,
    ``,
    ``,
    `https://archive.li/AXLKR`,
    ``,
    ``,
    ``,
    `maybe we're missing something like an attack based on religious, ethnic or other affiliation, but which is not an organized attack, but one on one`,
  ],
  [
    `Political commentator Nebojša Krstić shared a photo of actor Nikola Kojo from the "Serbia against violence" protest held on May 27 on his Twitter profile. At the protest, Kojo carried a sign with the name of Major Omer Mehić, who died terribly in a helicopter crash in 2015, which remains unexplained but is speculated to be connected to the incompetence of the authorities. Krstić shared the photo and replaced the name on the banner with the message "Serbs suffer violence in Kosovo". Krstić has been active on Twitter for days, where he attacks the opposition and criticizes the protests.`,
    `Nebojša Krstić fabricated a photo of actor Nikola Koja on Twitter`,
    `2023-05-29`,
    ``,
    `Public figures`,
    `Public figures`,
    `Fraud, threats and manipulations`,
    `Public misinformation`,
    `Content manipulation`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/CenzurisanoL/status/1663123104288190464?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1663221586021826560%7Ctwgr%5Eac34f6ca4d5296c5a26e9725546f7d3d47ec8da9%7Ctwcon%5Es3_&ref_url=https%3A%2F%2Fnova.rs%2Fvesti%2Fpolitika%2Fnebojsa-krstic-probio-dno-kada-je-napao-nikolu-koja-stigao-je-snazan-odgovor-glumca%2F`,
    `https://citymagazine.danas.rs/scena/drustvene-mreze/nebojsa-krstic-je-pokusao-da-bude-drustveno-angazovan-i-duhovit/`,
    ``,
    `https://archive.is/1lGMs`,
    `https://archive.li/jsBT2`,
    ``,
    ``,
    ``,
  ],
  [
    `Activist of the Gay Straight Alliance, Lazar Pavlović, who walked with his wife and child at the "Serbia Against Violence" protest wearing a "Vulture Dad" t-shirt as a response to the way the authorities characterized the protesters who were walking in the streets, was attacked on social media and in the media the very next day. Pavlović became the target of homophobic attacks, with old pictures from his Instagram profile also being published.`,
    `Activist Lazar Pavlović was the target of homophobic insults following the protest`,
    `2023-05-28`,
    ``,
    `Civil society`,
    `Media sector`,
    `Fraud, threats and manipulations`,
    `Character assassination`,
    `Organized attacks on networks targeting vulnerable communities (women, lgbtq+, ethnic minorities, refugees and migrants)`,
    `Discrimination and hate speech`,
    `Organized attacks on networks targeting vulnerable communities (women, lgbtq+, ethnic minorities, refugees and migrants)`,
    `Discrimination and hate speech`,
    `Attacks based on gender and sexual characteristics`,
    `Invasion of privacy`,
    `Collection, manipulation, dissemination and misuse of personal data`,
    `Targeted and organized attacks on communities`,
    `Organized attacks on networks targeting vulnerable communities (women, lgbtq+, ethnic minorities, refugees and migrants)`,
    `https://twitter.com/dasezna/status/1663167547569582080`,
    `https://www.politika.rs/sr/clanak/555094/Ko-je-Lazar-Pavlovic-koji-je-nosio-majicu-lesinar-tata`,
    `https://twitter.com/DrugaSrbijaBis/status/1662702953554227200?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1662702953554227200%7Ctwgr%5E480e50488220ad2061f8085f9e56fb4eb2f42cc8%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fwww.alo.rs%2Fvesti%2Fpolitika%2F764869%2Fgej-i-opozicionar-po-potrebi-a-sad-postao-porodicni-covek-ko-je-lazar-pavlovic-i-sta-je-radio-na-protestu%2Fvest`,
    `https://archive.li/OGzKN`,
    `https://archive.li/bbU74`,
    `https://archive.li/61g5i`,
    ``,
    `collection, manipulation, dissemination and misuse of personal data?`,
  ],
  [
    `A few days after the mass shooting at the "Vladislav Ribnikar" elementary school in Belgrade, a video appeared on TikTok that allegedly shows the students of that school bullying the killer, with captions saying that the video shows the moments before the massacre or that this is just an example of the treatment the perpetrator was subject to at the school. It was quickly discovered that the video was actually from a school in Russia and had been released several months ago and was in no way connected to the tragedy. Despite this knowledge, the video circulated widely on the social network and can still be found on several accounts expressing sympathy for the killer.`,
    `Fake bullying video circulated on TikTok after mass murder at elementary school`,
    `2023-05-06`,
    ``,
    `The public`,
    `Unknown`,
    `Fraud, threats and manipulations`,
    `Public misinformation`,
    `Content manipulation`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://vm.tiktok.com/ZM22b3sJU/?t=2`,
    ``,
    ``,
    `https://archive.li/cZ9UV`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Citizens' Association Fruškać lost a first-instance case before the High Court in Belgrade due to the sharing of a photo in which they were tagged via Instagram stories. The Association was obliged by the verdict to pay 115,000 dinars in the name of copyright damages and court costs and announced an appeal against the judgment.`,
    `Judgment against citizens' association for sharing a photo on Instagram`,
    `2023-05-30`,
    ``,
    `Civil society`,
    `Individual`,
    `Fraud, threats and manipulations`,
    `Limiting freedom of expression`,
    `Abuse of legal mechanisms`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.facebook.com/story.php?story_fbid=pfbid02TYFtgSgpHo1UEdZxwmWPvFD92DiXaTkf679Rf6guAVrVGUPvkfQYCw5m1SFzbQtxl&id=1008229337&mibextid=qC1gEa`,
    ``,
    ``,
    `(screenshot)`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Two fake profiles that were sending explicit messages to women on Instagram have been discovered. A number of women who received messages from these profiles came forward on Twitter and some determined that the photos used on the accounts were taken off the Internet. The profiles of Aleksandar Božić and Popović Vlada present themselves as if they are members of the Faculty of Orthodox Theology in Belgrade.`,
    `Fake profiles harass women on Instagram`,
    `2023-04-05`,
    ``,
    `The public`,
    `Unknown`,
    `Fraud, threats and manipulations`,
    `Endangering security`,
    `Cyber-mobbing`,
    ``,
    ``,
    ``,
    ``,
    `Harassment`,
    `Cyber-mobbing`,
    ``,
    ``,
    `https://twitter.com/jasampicko_/status/1643712979412697088`,
    ``,
    ``,
    `https://archive.li/Op9ca`,
    `(screenshot 1&2)`,
    ``,
    ``,
    `endangering security / harrassment`,
  ],
  [
    `On Tuesday, May 23rd, a new series of anonymous and false bomb threat reports targeted schools in Novi Sad, Niš, Kragujevac, Kruševac, Čačak, and Gornji Milanovac. According to the Ministry of Interior (MUP) data, there were even 200 reports of bomb threats received on that day. The police investigated each report and determined that they were all false. Additionally, bomb threats were also received by the Military Medical Academy, the Clinical Hospital Center Zvezdara, and the Belgrade Zoo.`,
    `Anonymous and false bomb threat reports via email`,
    `2023-05-17`,
    ``,
    `Public sector`,
    `Unknown`,
    `Cyber incidents`,
    `Online scams`,
    `Social engineering (phishing/vishing/smishing, impersonation)`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.bbc.com/serbian/lat/svet-65619123`,
    ``,
    ``,
    `https://archive.li/eUAnx`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `The website of JUGpress recently faced a significant attack and attempted breach of their system. However, thanks to the swift response of their technical support team, the consequences were successfully mitigated. This media organization has previously been targeted by similar attacks, raising suspicions that this incident is yet another attempt to exert pressure due to their objective, professional, and unbiased editorial policy. The JUGpress website was once again under a technical attack on June 21st, and they managed to recover successfully after this incident.`,
    `JUGpress Website Successfully Defends Against Serious Cyber Attack`,
    `2023-05-15`,
    `2023-05-17`,
    `Media sector`,
    `Unknown`,
    `Cyber incidents`,
    `Disabled services`,
    `DoS/DDoS`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.facebook.com/ljiljana.stojanovic.1654/posts/pfbid02SyGkA7zyN5CcPTatfsi1U6FHN82LAhyeNcnh54TJ8YcRAnTAvPC1SWAiqVuJJQNYl`,
    `https://jugpress.com/sajt-regionalne-informativne-agencije-jugpress-ponovo-radi/`,
    `https://www.facebook.com/ljiljana.stojanovic.1654/posts/pfbid0R5yB6wSMisHip2dYfwkBg77RG1V8DDogZAt153a1VyXA2TbVdNXb7Mevt5Cou476l `,
    `https://archive.li/DobTO`,
    `https://archive.li/yWAfM`,
    `https://archive.li/uESSY`,
    ``,
    ``,
  ],
  [
    `The National Computer Emergency Response Team (CERT) of Serbia has issued a warning regarding a new phishing campaign targeting users of postal services. Users are receiving fraudulent SMS messages claiming that their package could not be delivered due to alleged unpaid customs fees. The message instructs them to open a link provided in the SMS, which redirects them to a fake webpage requesting their banking card information. By providing these details, attackers gain access to the users' bank accounts and can steal their money.`,
    `Phishing Campaign Targeting Postal Service Users`,
    `2023-05-10`,
    ``,
    `The public`,
    `Unknown`,
    `Cyber incidents`,
    `Online scams`,
    `Fake resources (fake website, email)`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.cert.rs/rs/obavestenje/1042-Fi%C5%A1ing-napadi-putem-SMS-poruka-na-korisnike-po%C5%A1tanskih-usluga.html`,
    ``,
    ``,
    `https://archive.li/HczV2`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `A photo of a false letter of resignation of the Minister of Mining and Energy Dubravka Đedović appeared on Twitter. It was soon discovered that the letter was fabricated and that the Minister did not resign. The signature and seal were missing from the letter and users quickly realized that it was fake news.`,
    `False letter of resignation of MP published on Twitter`,
    `2023-06-08`,
    ``,
    `The public`,
    `Unknown`,
    `Fraud, threats and manipulations`,
    `Public misinformation`,
    `Creating and sharing fake content`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/andrejic_bojan/status/1666594733622280192`,
    ``,
    ``,
    `https://archive.li/XjdYz`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Member of the Presidency of the Serbian Progressive Party and Vice-President of the National Assembly, Sandra Božić, attacked actor Milan Marić on Twitter a day after Marić spoke at the "Serbia against violence" protest. Božić called out the actor for his so-called "anti-Serb" views and shared a video in which Marić reads the statements of victims and witnesses of the genocide in Srebrenica from the trial of Radislav Krstić and Ratko Mladić, which was created as part of the Hague Tribunal project. Marić was the target of criticism because of this video before, but after joining the protests, he again attracted the public's attention.`,
    `Vice President of the National Assembly targets actor on Twitter for supporting protests`,
    `2023-06-10`,
    ``,
    `Public figures`,
    `Political subject`,
    `Fraud, threats and manipulations`,
    `Character assassination`,
    `Verbal attacks`,
    `Limiting freedom of expression`,
    `Verbal attacks`,
    `Endangering security`,
    `Cyber-mobbing`,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/BozicSandra/status/1667316490964533248`,
    ``,
    ``,
    `https://archive.ph/8khkt`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `After she supported the protests, actress Tamara Dragićević received numerous threats on Instagram for weeks. In the most recent messages, commenters told the actress they knew that her children were on a school trip and when they had their recitals. The threats were reported to the police.`,
    `Serbian Actress and her children received threats on Instagram`,
    `2023-06-10`,
    ``,
    `Public figures`,
    `Unknown`,
    `Fraud, threats and manipulations`,
    `Endangering security`,
    `Verbal attacks`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.instagram.com/p/CtWNWWrsOH5/?igshid=MzRlODBiNWFlZA%3D%3D`,
    `https://n1info.rs/vesti/glumici-tamari-dragicevic-stigle-pretnje-zbog-podrske-protestu-spominju-i-decu/`,
    ``,
    `https://archive.li/dtHTT`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `A nuclear engineer was dismissed from the Directorate for Radiation and Nuclear Safety and Security due to her tweets on the account under the pseudonym "Mila Sila". The tweets contained criticism of the behavior of high-ranking state officials, and the engineer was previously targeted by disciplinary measures at the workplace because of her tweets.`,
    `Nuclear engineer fired because of critical tweets about the government`,
    `2023-06-09`,
    ``,
    `The public`,
    `Authority figures`,
    `Fraud, threats and manipulations`,
    `Limiting freedom of expression`,
    `Retaliation`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.vreme.com/kolumna/slucaj-nuklearne-inzenjerke-otkaz-zbog-politicki-nepodobnih-tvitova/`,
    ``,
    ``,
    `https://archive.li/sM4nd`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `The independent theater "Reflektor Teatar" published a Twitter thread about the 90s and the wars in the territory of the former Yugoslavia and invited citizens to share what they know about their parents' youth. In the responses to their tweets, a large number of insults and threats addressed to the theater followed.`,
    `Theater receives threats and insults on Twitter`,
    `2023-06-13`,
    ``,
    `Civil society`,
    `Individual`,
    `Fraud, threats and manipulations`,
    `Endangering security`,
    `Verbal attacks`,
    `Limiting freedom of expression`,
    `Verbal attacks`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/reflektorteatar/status/1668588910253862913?t=eVkbT4EVW__tq_GJSNYfag&s=35`,
    ``,
    ``,
    `https://archive.li/kFEbD`,
    ``,
    ``,
    ``,
    `another subcategory maybe`,
  ],
  [
    `An article about the decision of the Management Board od the Radio Television of Vojvodina to appoint a new acting director instead of a new general director has been deleted from the website of that provincial institution. The news was also deleted from other media portals from Vojvodina such as Dnevnik and Vojvodina uživo.`,
    `Article about the RTV Managing Board decision removed from media websites`,
    `2023-06-21`,
    ``,
    `The public`,
    `Media sector`,
    `Fraud, threats and manipulations`,
    `Self censorship`,
    `Content removal`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.cenzolovka.rs/drzava-i-mediji/skandal-oko-izbora-direktora-rtv-nekom-se-odluka-upravnog-odbora-nije-dopala-vest-izbrisana-sa-nekoliko-portala/`,
    ``,
    ``,
    `https://archive.li/aLsB5`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `A popular YouTuber posted a live stream in which he scrolled through Tinder profiles of girls and commented on them. In the video, he used insults and inappropriate jokes against a trans girl who reported abuse to the organization Da se zna.`,
    `Popular YouTuber insluts trans person in his livestream`,
    `2023-06-21`,
    ``,
    `The public`,
    `Public figures`,
    `Fraud, threats and manipulations`,
    `Character assassination`,
    `Organized attacks on networks targeting vulnerable communities (women, lgbtq+, ethnic minorities, refugees and migrants)`,
    `Discrimination and hate speech`,
    `Organized attacks on networks targeting vulnerable communities (women, lgbtq+, ethnic minorities, refugees and migrants)`,
    `Discrimination and hate speech`,
    `Attacks based on gender and sexual characteristics`,
    `Invasion of privacy`,
    `Collection, manipulation, dissemination and misuse of personal data`,
    `Targeted and organized attacks on communities`,
    `Organized attacks on networks targeting vulnerable communities (women, lgbtq+, ethnic minorities, refugees and migrants)`,
    `https://www.instagram.com/p/CttgvTiMaEa/?igshid=MTc4MmM1YmI2Ng%3D%3D`,
    ``,
    ``,
    `(screenshot)`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `The National Bank of Serbia warns citizens to be cautious if they receive SMS messages from unknown phone numbers, especially those with the country code +33. The sender falsely presents themselves as a provider of services for companies such as Netflix, Serbian Post, DHL, and similar ones, but it is a scam. The websites linked in the SMS messages are fraudulent.`,
    `Scam SMS Messages Impersonating Service Providers`,
    `2023-06-27`,
    ``,
    `The public`,
    `Unknown`,
    `Cyber incidents`,
    `Online scams`,
    `Fake resources (fake website, email)`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://www.021.rs/story/Info/Srbija/345058/NBS-upozorila-na-SMS-prevaru-Obratite-paznju-na-nepoznate-brojeve.html`,
    ``,
    ``,
    `https://archive.li/li9Ff`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `In the wake of the support of a number of actors to the protests against violence that have been going on for weeks, videos began to circulate on social networks announcing how much money these public figures receive from the state operator Telekom Srbija for filming series and movies under their production. It is not known where this information came from, but the attacks on the networks followed after MPs read similar lists in the Parliament.`,
    `Actors and actresses suffer organized attacks on social media`,
    `2023-06-11`,
    ``,
    `Public figures`,
    `Unknown`,
    `Fraud, threats and manipulations`,
    `Endangering security`,
    `Collection, manipulation, dissemination and misuse of personal data`,
    `Limiting freedom of expression`,
    `Verbal attacks`,
    `Endangering security`,
    `Cyber-mobbing`,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/PrijateljNaroda/status/1667978013093314565`,
    ``,
    ``,
    `https://archive.li/g1Pqz`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `A private video that folk singer Ana Nikolić sent to Saša Mirković, the director of Hype Television, whom she addresses directly in the video, was published on the tv station's social media profiles without her consent. The video was shared with a description in which the television's social media team implied that the singer, who was visibly unwell in the recording, had been using various substances, and it was clear that the video was intended for a specific person and was not meant to be shared. The video quickly started circulating around social media and was being shared by a number of accounts.`,
    `Private video of singer posted on social media without her consent`,
    `2023-07-01`,
    ``,
    `Public figures`,
    `Public figures`,
    `Fraud, threats and manipulations`,
    `Character assassination`,
    `Distribution of content without consent`,
    ``,
    ``,
    ``,
    ``,
    `Invasion of privacy`,
    `Non-consensual distribution of content (including intimate content)`,
    `Invasion of privacy`,
    `Collection, manipulation, dissemination and misuse of personal data`,
    `https://twitter.com/Sivaeminencija2/status/1675091170932801536?s=20`,
    `https://twitter.com/Tajniznak26/status/1675093695643648003`,
    ``,
    `(screenshot 1&2)`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `The website of Južne vesti experienced a severe DDoS attack on July 3rd. Fortunately, the consequences were successfully mitigated. They informed their readers about the attack through their Twitter account.`,
    `The website of a regional media outlet was under a technical attack`,
    `2023-07-03`,
    `2023-07-03`,
    `Media sector`,
    `Unknown`,
    `Cyber incidents`,
    `Disabled services`,
    `DoS/DDoS`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/juznevesti/status/1675874913415049218?t=PgKPl5roQ26kLzBzFL32Kg&s=09`,
    ``,
    ``,
    `(screenshot-juznevesti)`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Numerous transphobic comments were published on social media accounts organization Da se zna regarding the murder of trans girl Noa Milivojev. In some of these comments, Noah was deadnamed, i.e. her name before the transition was written. `,
    `Transphobia and deadnaming of a murdered trans girl on social networks`,
    `2023-07-06`,
    ``,
    `The public`,
    `Individual`,
    `Fraud, threats and manipulations`,
    `Discrimination and hate speech`,
    `Attacks based on gender and sexual characteristics`,
    ``,
    ``,
    ``,
    ``,
    `Invasion of privacy`,
    `Collection, manipulation, dissemination and misuse of personal data`,
    ``,
    ``,
    `https://twitter.com/dasezna/status/1676979327173271552?t=6fy-eoIWOgGolV_rQ_k6tA&s=35`,
    ``,
    ``,
    `https://archive.li/KRfCx`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `Twitter user @protivdictature published a list of accounts that are allegedly bots of the Serbian Progressive Party. The list contains the names, surnames and city of the person behind the account as well as the account in question. It is still not clear where the list came from, the account he published claims he paid for it and received it from the Serbian Progressive Party. In the days after the list was published, other Twitter users claimed to have found acquaintances and family members on the lists and in some cases stated that people on the lists had suffered physical violence.`,
    `List of SNS bot accounts published on Twitter, source unknown`,
    `2023-07-06`,
    ``,
    `Mass casualty`,
    `Private person`,
    `Privacy and data protection`,
    `Disclosure of data`,
    `Posting on a social network, blog, chat app`,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    ``,
    `https://twitter.com/protivdictature/status/1677054817649213440?s=46`,
    ``,
    ``,
    `https://archive.li/BWQHF`,
    ``,
    ``,
    ``,
    ``,
  ],
  [
    `A large number of pictures and personal data of people whose names were on the list of bots published on July 6 on Twitter were exposed to various verbal attacks and threats on the networks in the previous days. In addition to general attacks, women from these lists have also been the target of misogynistic and offensive comments that are more gender-based than anything else.`,
    `Women from the bot list are targeted with misogynistic comments and threats on social media`,
    `2023-07-10`,
    ``,
    `The public`,
    `Individual`,
    `Fraud, threats and manipulations`,
    `Discrimination and hate speech`,
    `Collection, manipulation, dissemination and misuse of personal data`,
    `Discrimination and hate speech`,
    `Attacks based on gender and sexual characteristics`,
    ``,
    ``,
    `Harassment`,
    `Direct threats of violence, including threats of a sexual or physical nature`,
    `Invasion of privacy`,
    `Collection, manipulation, dissemination and misuse of personal data`,
    `https://twitter.com/MisoIlic032/status/1678506098171555840?s=20`,
    `https://twitter.com/kaldrma70/status/1678479739944681474?s=20`,
    ``,
    `https://archive.li/IqSmY`,
    `https://archive.ph/fd0vH`,
    ``,
    ``,
    ``,
  ],
  [
    `Content creator Istok Pavlović posted a video on his TikTok in which he used an image from an intimate video of singer Severina Vučković from 2004 to demonstrate the possibilities of new AI tools in Photoshop. After the video was met with outrage on the networks, Pavlović published an explanation where he did not apologize, but tried to justify the use of the photo.`,
    `Creator used singer's intimate recording without consent to promote his content`,
    `2023-07-09`,
    ``,
    `Public figures`,
    `Public figures`,
    `Fraud, threats and manipulations`,
    `Character assassination`,
    `Non-consensual distribution of intimate content`,
    ``,
    ``,
    ``,
    ``,
    `Invasion of privacy`,
    `Non-consensual distribution of content (including intimate content)`,
    ``,
    ``,
    `https://twitter.com/preputiumpenis/status/1678143335226044420?s=46`,
    ``,
    ``,
    `https://archive.ph/mg5Ux`,
    ``,
    ``,
    ``,
    ``,
  ],
];
